-- schema.sqlite.sql: the complete SQLite schema from scratch, equivalent to
-- running every up migration (0001..0010) in order. A fresh install can apply
-- this single file instead of the incremental runner; Store.Install does exactly
-- that and then stamps schema_migrations so a later Migrate is a no-op.
--
-- This file is generated by hand but guarded: TestSchemaFileMatchesMigrations
-- builds one database with Migrate and one with this file, then compares their
-- normalized structure (tables, columns, indexes, triggers). Keep the two in
-- lockstep; when you add a migration, fold its up body into the matching CREATE
-- here in column-append order so the comparison stays green.
--
-- The ALTER TABLE ADD COLUMN statements the migrations use are folded into the
-- CREATE statements here, with the added columns kept in migration order at the
-- end of each table so the column layout matches byte for byte.

CREATE TABLE id_allocator (
    id         INTEGER PRIMARY KEY CHECK (id = 1),
    high_water INTEGER NOT NULL DEFAULT 0
);
INSERT INTO id_allocator (id, high_water) VALUES (1, 0);

CREATE TABLE users (
    pk            INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id         INTEGER NOT NULL UNIQUE,
    login         TEXT    NOT NULL,
    type          TEXT    NOT NULL DEFAULT 'User',
    name          TEXT,
    email         TEXT,
    site_admin    INTEGER NOT NULL DEFAULT 0,
    password_hash TEXT,
    created_at    TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TEXT,
    company          TEXT,
    blog             TEXT    NOT NULL DEFAULT '',
    location         TEXT,
    bio              TEXT,
    hireable         INTEGER,
    twitter_username TEXT,
    public_repos     INTEGER NOT NULL DEFAULT 0,
    public_gists     INTEGER NOT NULL DEFAULT 0,
    followers        INTEGER NOT NULL DEFAULT 0,
    following        INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX users_login_lower_uq ON users (lower(login)) WHERE deleted_at IS NULL;

CREATE TABLE repositories (
    pk                INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id             INTEGER NOT NULL UNIQUE,
    owner_pk          INTEGER NOT NULL REFERENCES users(pk) ON DELETE CASCADE,
    name              TEXT    NOT NULL,
    description       TEXT,
    private           INTEGER NOT NULL DEFAULT 0,
    fork              INTEGER NOT NULL DEFAULT 0,
    default_branch    TEXT    NOT NULL DEFAULT 'main',
    next_issue_number INTEGER NOT NULL DEFAULT 1,
    open_issues_count INTEGER NOT NULL DEFAULT 0,
    pushed_at         TEXT,
    lock_version      INTEGER NOT NULL DEFAULT 0,
    created_at        TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TEXT,
    homepage      TEXT,
    has_issues    INTEGER NOT NULL DEFAULT 1,
    has_projects  INTEGER NOT NULL DEFAULT 1,
    has_wiki      INTEGER NOT NULL DEFAULT 1,
    has_downloads INTEGER NOT NULL DEFAULT 1,
    archived      INTEGER NOT NULL DEFAULT 0,
    disabled      INTEGER NOT NULL DEFAULT 0,
    is_template   INTEGER NOT NULL DEFAULT 0,
    next_milestone_number INTEGER NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX repos_owner_name_uq ON repositories (owner_pk, lower(name)) WHERE deleted_at IS NULL;

CREATE TABLE oauth_apps (
    pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id           TEXT    NOT NULL UNIQUE,
    client_secret_hash  BLOB,
    name                TEXT    NOT NULL,
    owner_pk            INTEGER REFERENCES users(pk) ON DELETE CASCADE,
    device_flow_enabled INTEGER NOT NULL DEFAULT 0,
    created_at          TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tokens (
    pk              INTEGER PRIMARY KEY AUTOINCREMENT,
    user_pk         INTEGER REFERENCES users(pk) ON DELETE CASCADE,
    oauth_app_pk    INTEGER REFERENCES oauth_apps(pk) ON DELETE CASCADE,
    token_hash      BLOB    NOT NULL UNIQUE,
    token_prefix    TEXT    NOT NULL,
    last_eight      TEXT    NOT NULL,
    kind            TEXT    NOT NULL,
    scopes          TEXT    NOT NULL DEFAULT '',
    note            TEXT    NOT NULL DEFAULT '',
    expires_at      TEXT,
    revoked_at      TEXT,
    last_used_at    TEXT,
    created_at      TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 0012_github_apps: installation token linkage
    installation_pk INTEGER REFERENCES installations(pk) ON DELETE CASCADE,
    github_app_pk   INTEGER REFERENCES github_apps(pk) ON DELETE CASCADE,
    grant_json      TEXT
);

CREATE TABLE oauth_device_codes (
    pk               INTEGER PRIMARY KEY AUTOINCREMENT,
    device_code_hash BLOB    NOT NULL UNIQUE,
    user_code        TEXT    NOT NULL UNIQUE,
    oauth_app_pk     INTEGER REFERENCES oauth_apps(pk) ON DELETE CASCADE,
    scopes           TEXT    NOT NULL DEFAULT '',
    state            TEXT    NOT NULL DEFAULT 'pending',
    user_pk          INTEGER REFERENCES users(pk) ON DELETE SET NULL,
    interval_sec     INTEGER NOT NULL DEFAULT 5,
    last_polled_at   TEXT,
    expires_at       TEXT    NOT NULL,
    created_at       TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE jobs (
    pk           INTEGER PRIMARY KEY AUTOINCREMENT,
    kind         TEXT    NOT NULL,
    payload      TEXT    NOT NULL DEFAULT '{}',
    dedupe_key   TEXT,
    state        TEXT    NOT NULL DEFAULT 'queued',
    attempts     INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    run_after    TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error   TEXT,
    locked_at    TEXT,
    created_at   TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX jobs_dedupe_active_uq ON jobs (dedupe_key)
    WHERE dedupe_key IS NOT NULL AND state IN ('queued', 'running');
CREATE INDEX jobs_claim_idx ON jobs (run_after) WHERE state = 'queued';

CREATE TABLE labels (
    pk          INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id       INTEGER NOT NULL UNIQUE,
    repo_pk     INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    name        TEXT    NOT NULL,
    color       TEXT    NOT NULL DEFAULT 'ededed',
    description TEXT,
    is_default  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX labels_repo_name_uq ON labels (repo_pk, lower(name));

CREATE TABLE milestones (
    pk          INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id       INTEGER NOT NULL UNIQUE,
    repo_pk     INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    number      INTEGER NOT NULL,
    title       TEXT    NOT NULL,
    description TEXT,
    state       TEXT    NOT NULL DEFAULT 'open',
    due_on      TEXT,
    creator_pk  INTEGER REFERENCES users(pk),
    closed_at   TEXT,
    created_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX milestones_repo_number_uq ON milestones (repo_pk, number);

CREATE TABLE issues (
    pk                 INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id              INTEGER NOT NULL UNIQUE,
    repo_pk            INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    number             INTEGER NOT NULL,
    is_pull            INTEGER NOT NULL DEFAULT 0,
    title              TEXT    NOT NULL,
    body               TEXT,
    user_pk            INTEGER NOT NULL REFERENCES users(pk),
    state              TEXT    NOT NULL DEFAULT 'open',
    state_reason       TEXT,
    milestone_pk       INTEGER REFERENCES milestones(pk) ON DELETE SET NULL,
    locked             INTEGER NOT NULL DEFAULT 0,
    active_lock_reason TEXT,
    comments_count     INTEGER NOT NULL DEFAULT 0,
    closed_at          TEXT,
    closed_by_pk       INTEGER REFERENCES users(pk),
    lock_version       INTEGER NOT NULL DEFAULT 0,
    created_at         TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at         TEXT
);
CREATE UNIQUE INDEX issues_repo_number_uq ON issues (repo_pk, number);
CREATE INDEX issues_repo_state_idx ON issues (repo_pk, state) WHERE deleted_at IS NULL;
CREATE INDEX issues_repo_pull_idx ON issues (repo_pk, is_pull) WHERE deleted_at IS NULL;

CREATE TABLE issue_comments (
    pk         INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id      INTEGER NOT NULL UNIQUE,
    issue_pk   INTEGER NOT NULL REFERENCES issues(pk) ON DELETE CASCADE,
    user_pk    INTEGER NOT NULL REFERENCES users(pk),
    body       TEXT    NOT NULL,
    created_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
);
CREATE INDEX issue_comments_issue_idx ON issue_comments (issue_pk, created_at) WHERE deleted_at IS NULL;

CREATE TABLE issue_labels (
    issue_pk INTEGER NOT NULL REFERENCES issues(pk) ON DELETE CASCADE,
    label_pk INTEGER NOT NULL REFERENCES labels(pk) ON DELETE CASCADE,
    PRIMARY KEY (issue_pk, label_pk)
);

CREATE TABLE assignees (
    issue_pk INTEGER NOT NULL REFERENCES issues(pk) ON DELETE CASCADE,
    user_pk  INTEGER NOT NULL REFERENCES users(pk) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (issue_pk, user_pk)
);

CREATE TABLE reactions (
    pk           INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id        INTEGER NOT NULL UNIQUE,
    subject_type TEXT    NOT NULL,
    subject_pk   INTEGER NOT NULL,
    user_pk      INTEGER NOT NULL REFERENCES users(pk) ON DELETE CASCADE,
    content      TEXT    NOT NULL,
    created_at   TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX reactions_subject_user_content_uq
    ON reactions (subject_type, subject_pk, user_pk, content);
CREATE INDEX reactions_subject_idx ON reactions (subject_type, subject_pk);

CREATE TABLE issue_events (
    pk         INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id      INTEGER NOT NULL UNIQUE,
    repo_pk    INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    issue_pk   INTEGER NOT NULL REFERENCES issues(pk) ON DELETE CASCADE,
    actor_pk   INTEGER REFERENCES users(pk),
    event      TEXT    NOT NULL,
    payload    TEXT    NOT NULL DEFAULT '{}',
    created_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX issue_events_issue_idx ON issue_events (issue_pk, created_at);
CREATE INDEX issue_events_repo_idx ON issue_events (repo_pk, created_at);

CREATE TABLE pull_requests (
    pk                      INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id                   INTEGER NOT NULL UNIQUE,
    issue_pk                INTEGER NOT NULL UNIQUE REFERENCES issues(pk) ON DELETE CASCADE,
    repo_pk                 INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    base_ref                TEXT    NOT NULL,
    base_sha                TEXT    NOT NULL,
    head_ref                TEXT    NOT NULL,
    head_sha                TEXT    NOT NULL,
    head_repo_pk            INTEGER REFERENCES repositories(pk) ON DELETE SET NULL,
    draft                   INTEGER NOT NULL DEFAULT 0,
    maintainer_can_modify   INTEGER NOT NULL DEFAULT 0,
    merged                  INTEGER NOT NULL DEFAULT 0,
    merged_at               TEXT,
    merged_by_pk            INTEGER REFERENCES users(pk),
    merge_commit_sha        TEXT,
    mergeable               INTEGER,
    mergeable_state         TEXT    NOT NULL DEFAULT 'unknown',
    rebaseable              INTEGER,
    additions               INTEGER NOT NULL DEFAULT 0,
    deletions               INTEGER NOT NULL DEFAULT 0,
    changed_files           INTEGER NOT NULL DEFAULT 0,
    commits_count           INTEGER NOT NULL DEFAULT 0,
    mergeability_checked_at TEXT,
    created_at              TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX pull_requests_repo_idx ON pull_requests (repo_pk);
CREATE INDEX pull_requests_open_head_idx ON pull_requests (repo_pk, head_ref) WHERE merged = 0;

CREATE TABLE pull_request_reviews (
    pk                INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id             INTEGER NOT NULL UNIQUE,
    pull_pk           INTEGER NOT NULL REFERENCES pull_requests(pk) ON DELETE CASCADE,
    repo_pk           INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    user_pk           INTEGER NOT NULL REFERENCES users(pk),
    state             TEXT    NOT NULL,
    body              TEXT    NOT NULL DEFAULT '',
    commit_id         TEXT    NOT NULL DEFAULT '',
    dismissed_message TEXT,
    submitted_at      TEXT,
    created_at        TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX pull_request_reviews_pull_idx ON pull_request_reviews (pull_pk);
CREATE UNIQUE INDEX pull_request_reviews_pending_idx
    ON pull_request_reviews (pull_pk, user_pk) WHERE state = 'PENDING';

CREATE TABLE pull_request_review_comments (
    pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id               INTEGER NOT NULL UNIQUE,
    review_pk           INTEGER NOT NULL REFERENCES pull_request_reviews(pk) ON DELETE CASCADE,
    pull_pk             INTEGER NOT NULL REFERENCES pull_requests(pk) ON DELETE CASCADE,
    repo_pk             INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    user_pk             INTEGER NOT NULL REFERENCES users(pk),
    path                TEXT    NOT NULL,
    side                TEXT    NOT NULL DEFAULT 'RIGHT',
    line                INTEGER,
    start_line          INTEGER,
    start_side          TEXT,
    original_line       INTEGER,
    original_start_line INTEGER,
    position            INTEGER,
    original_position   INTEGER,
    commit_id           TEXT    NOT NULL DEFAULT '',
    original_commit_id  TEXT    NOT NULL DEFAULT '',
    in_reply_to_pk      INTEGER REFERENCES pull_request_review_comments(pk) ON DELETE SET NULL,
    diff_hunk           TEXT    NOT NULL DEFAULT '',
    subject_type        TEXT    NOT NULL DEFAULT 'line',
    body                TEXT    NOT NULL,
    resolved            INTEGER NOT NULL DEFAULT 0,
    resolved_by_pk      INTEGER REFERENCES users(pk),
    created_at          TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX pull_request_review_comments_pull_idx ON pull_request_review_comments (pull_pk);
CREATE INDEX pull_request_review_comments_review_idx ON pull_request_review_comments (review_pk);

CREATE TABLE commit_statuses (
    pk          INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id       INTEGER NOT NULL UNIQUE,
    repo_pk     INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    sha         TEXT    NOT NULL,
    state       TEXT    NOT NULL,
    context     TEXT    NOT NULL DEFAULT 'default',
    target_url  TEXT,
    description TEXT,
    creator_pk  INTEGER REFERENCES users(pk),
    created_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX commit_statuses_sha_idx ON commit_statuses (repo_pk, sha);

CREATE TABLE check_suites (
    pk         INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id      INTEGER NOT NULL UNIQUE,
    repo_pk    INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    head_sha   TEXT    NOT NULL,
    app_slug   TEXT    NOT NULL DEFAULT 'githome',
    status     TEXT    NOT NULL DEFAULT 'queued',
    conclusion TEXT,
    created_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX check_suites_key_idx ON check_suites (repo_pk, head_sha, app_slug);

CREATE TABLE check_runs (
    pk             INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id          INTEGER NOT NULL UNIQUE,
    suite_pk       INTEGER NOT NULL REFERENCES check_suites(pk) ON DELETE CASCADE,
    repo_pk        INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    head_sha       TEXT    NOT NULL,
    name           TEXT    NOT NULL,
    status         TEXT    NOT NULL DEFAULT 'queued',
    conclusion     TEXT,
    details_url    TEXT,
    external_id    TEXT,
    output_title   TEXT,
    output_summary TEXT,
    output_text    TEXT,
    started_at     TEXT,
    completed_at   TEXT,
    created_at     TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX check_runs_sha_idx ON check_runs (repo_pk, head_sha);
CREATE INDEX check_runs_suite_idx ON check_runs (suite_pk);

CREATE TABLE pull_request_check_state (
    pull_pk         INTEGER PRIMARY KEY REFERENCES pull_requests(pk) ON DELETE CASCADE,
    review_decision TEXT,
    rollup_state    TEXT    NOT NULL DEFAULT 'EXPECTED',
    updated_at      TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events (
    pk         INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id      INTEGER NOT NULL UNIQUE,
    event      TEXT    NOT NULL,
    action     TEXT    NOT NULL DEFAULT '',
    actor_pk   INTEGER NOT NULL REFERENCES users(pk),
    repo_pk    INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    issue_pk   INTEGER REFERENCES issues(pk) ON DELETE CASCADE,
    payload    TEXT    NOT NULL DEFAULT '{}',
    public     INTEGER NOT NULL DEFAULT 1,
    created_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX events_repo_idx ON events (repo_pk, pk DESC);
CREATE INDEX events_actor_idx ON events (actor_pk, pk DESC);
CREATE INDEX events_issue_idx ON events (issue_pk, pk);

CREATE TABLE webhooks (
    pk            INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id         INTEGER NOT NULL UNIQUE,
    repo_pk       INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    name          TEXT    NOT NULL DEFAULT 'web',
    url           TEXT    NOT NULL,
    content_type  TEXT    NOT NULL DEFAULT 'json',
    secret        TEXT,
    insecure_ssl  INTEGER NOT NULL DEFAULT 0,
    active        INTEGER NOT NULL DEFAULT 1,
    events        TEXT    NOT NULL DEFAULT '["push"]',
    last_response TEXT,
    created_at    TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX webhooks_repo_idx ON webhooks (repo_pk);

CREATE TABLE webhook_deliveries (
    pk               INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id            INTEGER NOT NULL UNIQUE,
    webhook_pk       INTEGER NOT NULL REFERENCES webhooks(pk) ON DELETE CASCADE,
    guid             TEXT    NOT NULL,
    event            TEXT    NOT NULL,
    action           TEXT    NOT NULL DEFAULT '',
    status_code      INTEGER,
    request_url      TEXT    NOT NULL DEFAULT '',
    request_headers  TEXT    NOT NULL DEFAULT '{}',
    request_body     TEXT    NOT NULL DEFAULT '',
    response_headers TEXT    NOT NULL DEFAULT '{}',
    response_body    TEXT    NOT NULL DEFAULT '',
    duration_ms      INTEGER NOT NULL DEFAULT 0,
    redelivery       INTEGER NOT NULL DEFAULT 0,
    success          INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX webhook_deliveries_hook_idx ON webhook_deliveries (webhook_pk, pk DESC);
CREATE INDEX webhook_deliveries_guid_idx ON webhook_deliveries (guid);

CREATE VIRTUAL TABLE issues_fts USING fts5(
    title, body,
    content='issues', content_rowid='pk'
);

CREATE TRIGGER issues_ai AFTER INSERT ON issues BEGIN
    INSERT INTO issues_fts(rowid, title, body)
        VALUES (new.pk, new.title, COALESCE(new.body, ''));
END;

CREATE TRIGGER issues_ad AFTER DELETE ON issues BEGIN
    INSERT INTO issues_fts(issues_fts, rowid, title, body)
        VALUES ('delete', old.pk, old.title, COALESCE(old.body, ''));
END;

CREATE TRIGGER issues_au AFTER UPDATE OF title, body ON issues BEGIN
    INSERT INTO issues_fts(issues_fts, rowid, title, body)
        VALUES ('delete', old.pk, old.title, COALESCE(old.body, ''));
    INSERT INTO issues_fts(rowid, title, body)
        VALUES (new.pk, new.title, COALESCE(new.body, ''));
END;

CREATE VIRTUAL TABLE repos_fts USING fts5(
    name, description,
    content='repositories', content_rowid='pk'
);

CREATE TRIGGER repos_ai AFTER INSERT ON repositories BEGIN
    INSERT INTO repos_fts(rowid, name, description)
        VALUES (new.pk, new.name, COALESCE(new.description, ''));
END;

CREATE TRIGGER repos_ad AFTER DELETE ON repositories BEGIN
    INSERT INTO repos_fts(repos_fts, rowid, name, description)
        VALUES ('delete', old.pk, old.name, COALESCE(old.description, ''));
END;

CREATE TRIGGER repos_au AFTER UPDATE OF name, description ON repositories BEGIN
    INSERT INTO repos_fts(repos_fts, rowid, name, description)
        VALUES ('delete', old.pk, old.name, COALESCE(old.description, ''));
    INSERT INTO repos_fts(rowid, name, description)
        VALUES (new.pk, new.name, COALESCE(new.description, ''));
END;

CREATE INDEX issues_repo_created_number_idx
    ON issues (repo_pk, created_at DESC, number DESC)
    WHERE deleted_at IS NULL;

-- 0011_releases
ALTER TABLE repositories ADD COLUMN next_release_number INTEGER NOT NULL DEFAULT 1;

CREATE TABLE releases (
    pk               INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id            INTEGER NOT NULL UNIQUE,
    repo_pk          INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    tag_name         TEXT    NOT NULL,
    target_commitish TEXT    NOT NULL DEFAULT 'main',
    name             TEXT,
    body             TEXT,
    draft            INTEGER NOT NULL DEFAULT 0,
    prerelease       INTEGER NOT NULL DEFAULT 0,
    author_pk        INTEGER REFERENCES users(pk),
    lock_version     INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at     TEXT,
    updated_at       TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at       TEXT
);
CREATE UNIQUE INDEX releases_repo_tag_uq ON releases (repo_pk, tag_name) WHERE deleted_at IS NULL;
CREATE INDEX releases_repo_pub_idx ON releases (repo_pk, published_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE release_assets (
    pk             INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id          INTEGER NOT NULL UNIQUE,
    release_pk     INTEGER NOT NULL REFERENCES releases(pk) ON DELETE CASCADE,
    name           TEXT    NOT NULL,
    label          TEXT,
    content_type   TEXT    NOT NULL DEFAULT 'application/octet-stream',
    size           INTEGER NOT NULL DEFAULT 0,
    download_count INTEGER NOT NULL DEFAULT 0,
    uploader_pk    INTEGER REFERENCES users(pk),
    state          TEXT    NOT NULL DEFAULT 'open',
    lock_version   INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TEXT
);
CREATE UNIQUE INDEX release_assets_release_name_uq ON release_assets (release_pk, name) WHERE deleted_at IS NULL;

-- 0012_github_apps
CREATE TABLE github_apps (
    pk                  INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id               INTEGER NOT NULL UNIQUE,
    owner_pk            INTEGER NOT NULL REFERENCES users(pk) ON DELETE CASCADE,
    slug                TEXT    NOT NULL UNIQUE,
    name                TEXT    NOT NULL,
    client_id           TEXT    NOT NULL UNIQUE,
    client_secret_hash  BLOB,
    webhook_secret_hash BLOB,
    private_key_pem     BLOB    NOT NULL,
    permissions         TEXT    NOT NULL DEFAULT '{}',
    events              TEXT    NOT NULL DEFAULT '[]',
    created_at          TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE installations (
    pk                   INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id                INTEGER NOT NULL UNIQUE,
    app_pk               INTEGER NOT NULL REFERENCES github_apps(pk) ON DELETE CASCADE,
    account_pk           INTEGER NOT NULL REFERENCES users(pk) ON DELETE CASCADE,
    repository_selection TEXT    NOT NULL DEFAULT 'all',
    permissions          TEXT    NOT NULL DEFAULT '{}',
    events               TEXT    NOT NULL DEFAULT '[]',
    suspended_at         TEXT,
    created_at           TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX installations_app_account_uq ON installations (app_pk, account_pk);

CREATE TABLE installation_repositories (
    installation_pk INTEGER NOT NULL REFERENCES installations(pk) ON DELETE CASCADE,
    repo_pk         INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    PRIMARY KEY (installation_pk, repo_pk)
);

-- 0013_keys_protection
CREATE TABLE ssh_keys (
    pk           INTEGER PRIMARY KEY AUTOINCREMENT,
    db_id        INTEGER NOT NULL UNIQUE,
    user_pk      INTEGER NOT NULL REFERENCES users(pk) ON DELETE CASCADE,
    title        TEXT,
    key_type     TEXT    NOT NULL,
    public_key   TEXT    NOT NULL,
    fingerprint  TEXT    NOT NULL,
    read_only    INTEGER NOT NULL DEFAULT 0,
    repo_pk      INTEGER REFERENCES repositories(pk) ON DELETE CASCADE,
    last_used_at TEXT,
    created_at   TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX ssh_keys_fp_uq ON ssh_keys (fingerprint);

CREATE TABLE branch_protections (
    pk                          INTEGER PRIMARY KEY AUTOINCREMENT,
    repo_pk                     INTEGER NOT NULL REFERENCES repositories(pk) ON DELETE CASCADE,
    branch_pattern              TEXT    NOT NULL,
    require_pr_reviews          INTEGER NOT NULL DEFAULT 0,
    required_approving_count    INTEGER NOT NULL DEFAULT 0,
    dismiss_stale_reviews       INTEGER NOT NULL DEFAULT 0,
    require_code_owner_reviews  INTEGER NOT NULL DEFAULT 0,
    require_status_checks       INTEGER NOT NULL DEFAULT 0,
    require_branches_up_to_date INTEGER NOT NULL DEFAULT 0,
    status_check_contexts       TEXT    NOT NULL DEFAULT '[]',
    enforce_admins              INTEGER NOT NULL DEFAULT 0,
    restrictions_users          TEXT    NOT NULL DEFAULT '[]',
    restrictions_teams          TEXT    NOT NULL DEFAULT '[]',
    allow_force_pushes          INTEGER NOT NULL DEFAULT 0,
    allow_deletions             INTEGER NOT NULL DEFAULT 0,
    created_at                  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX branch_protections_repo_pattern_uq ON branch_protections (repo_pk, branch_pattern);
