package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"strings"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/domain"
	"github.com/tamnd/githome/nodeid"
	"github.com/tamnd/githome/presenter/gqlmodel"
)

// Author is the resolver for the author field. It loads the issue author
// through the per-request user dataloader so that concurrent nested field
// resolutions batch into one user query per request.
func (r *issueResolver) Author(ctx context.Context, obj *gqlmodel.Issue) (*gqlmodel.Actor, error) {
	if obj.UserPK == 0 {
		return nil, nil // ghost author
	}
	l := loadersFrom(ctx)
	if l == nil {
		return obj.Author, nil // fallback: loaders not wired (tests)
	}
	return l.Users.Load(ctx, obj.UserPK)
}

// Labels is the resolver for the labels field. It loads the issue's labels
// through the per-request label dataloader so that concurrent nested field
// resolutions batch into one label query per request.
func (r *issueResolver) Labels(ctx context.Context, obj *gqlmodel.Issue, first *int32, after *string) (*gqlmodel.LabelConnection, error) {
	l := loadersFrom(ctx)
	if l == nil {
		return obj.Labels, nil // fallback: loaders not wired (tests)
	}
	nodes, err := l.LabelsByIssue.Load(ctx, obj.PK)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.LabelConnection{Nodes: nodes, TotalCount: int32(len(nodes))}, nil
}

// Assignees is the resolver for the assignees field. GQLIssue fills the slice
// eagerly, so this resolver returns the pre-loaded connection directly.
func (r *issueResolver) Assignees(ctx context.Context, obj *gqlmodel.Issue, first *int32, after *string) (*gqlmodel.UserConnection, error) {
	if obj.Assignees != nil {
		return obj.Assignees, nil
	}
	return &gqlmodel.UserConnection{}, nil
}

// Milestone is the resolver for the milestone field. GQLIssue fills the
// milestone eagerly, so this resolver returns the pre-loaded value directly.
func (r *issueResolver) Milestone(ctx context.Context, obj *gqlmodel.Issue) (*gqlmodel.Milestone, error) {
	return obj.Milestone, nil
}

// Comments is the resolver for the comments field. It pages the issue's comments
// through the domain on demand, the way gh issue view selects them.
func (r *issueResolver) Comments(ctx context.Context, obj *gqlmodel.Issue, first *int32, after *string) (*gqlmodel.IssueCommentConnection, error) {
	page, err := issuePageArgs(first, after, nil, nil)
	if err != nil {
		return nil, err
	}
	comments, err := r.Issues.ListComments(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number), int64(page.page()), int64(page.limit))
	if err != nil {
		return nil, mapErr(err)
	}
	nodes := make([]*gqlmodel.IssueComment, 0, len(comments))
	for _, cm := range comments {
		nodes = append(nodes, r.URLs.GQLIssueComment(obj.RepoOwner, obj.RepoName, cm, r.NodeFormat))
	}
	total := int32(len(nodes))
	if obj.Comments != nil {
		total = obj.Comments.TotalCount
	}
	return &gqlmodel.IssueCommentConnection{Nodes: nodes, TotalCount: total}, nil
}

// CreateIssue is the resolver for the createIssue field. It opens an issue on the
// repository named by the input's node ID.
func (r *mutationResolver) CreateIssue(ctx context.Context, input generated.CreateIssueInput) (*generated.CreateIssuePayload, error) {
	repo, err := r.repoFromID(ctx, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	owner, name := repo.Owner.Login, repo.Name
	iss, err := r.Issues.CreateIssue(ctx, viewerID(ctx), owner, name, domain.IssueInput{
		Title: input.Title,
		Body:  input.Body,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.CreateIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// UpdateIssue is the resolver for the updateIssue field. It resolves the issue
// from its node ID and applies the partial patch from the input.
func (r *mutationResolver) UpdateIssue(ctx context.Context, input generated.UpdateIssueInput) (*generated.UpdateIssuePayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	patch := domain.IssuePatch{Title: input.Title, Body: input.Body}
	if input.State != nil {
		s := strings.ToLower(string(*input.State))
		patch.State = &s
	}
	if len(input.LabelIds) > 0 {
		names := make([]string, 0, len(input.LabelIds))
		for _, lid := range input.LabelIds {
			_, dbID, derr := nodeid.Decode(lid)
			if derr != nil {
				continue
			}
			lname, lerr := r.Issues.LabelNameByDBID(ctx, dbID)
			if lerr != nil {
				continue
			}
			names = append(names, lname)
		}
		patch.Labels = &names
	}
	if len(input.AssigneeIds) > 0 {
		logins := make([]string, 0, len(input.AssigneeIds))
		for _, uid := range input.AssigneeIds {
			_, pk, derr := nodeid.Decode(uid)
			if derr != nil {
				continue
			}
			login, lerr := r.Issues.UserLoginByPK(ctx, pk)
			if lerr != nil {
				continue
			}
			logins = append(logins, login)
		}
		patch.AssigneeLogins = &logins
	}
	if input.MilestoneID != nil {
		_, msNum, derr := nodeid.Decode(*input.MilestoneID)
		if derr == nil {
			patch.MilestoneNumber = &msNum
		}
	}
	iss, err := r.Issues.EditIssue(ctx, viewerID(ctx), owner, name, number, patch)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.UpdateIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// AddComment is the resolver for the addComment field. The subject ID is an issue
// node ID; the new comment is returned as a connection edge, the shape gh and the
// GitHub API both render.
func (r *mutationResolver) AddComment(ctx context.Context, input generated.AddCommentInput) (*generated.AddCommentPayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.SubjectID)
	if err != nil {
		return nil, err
	}
	cm, err := r.Issues.CreateComment(ctx, viewerID(ctx), owner, name, number, input.Body)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.AddCommentPayload{
		CommentEdge: &generated.IssueCommentEdge{
			Cursor: encodeCursor(0),
			Node:   r.URLs.GQLIssueComment(owner, name, cm, r.NodeFormat),
		},
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// CloseIssue is the resolver for the closeIssue field.
func (r *mutationResolver) CloseIssue(ctx context.Context, input generated.CloseIssueInput) (*generated.CloseIssuePayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.IssueID)
	if err != nil {
		return nil, err
	}
	state := "closed"
	patch := domain.IssuePatch{State: &state}
	if input.StateReason != nil {
		reason := closedStateReason(*input.StateReason)
		patch.StateReason = &reason
	}
	iss, err := r.Issues.EditIssue(ctx, viewerID(ctx), owner, name, number, patch)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.CloseIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// ReopenIssue is the resolver for the reopenIssue field.
func (r *mutationResolver) ReopenIssue(ctx context.Context, input generated.ReopenIssueInput) (*generated.ReopenIssuePayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.IssueID)
	if err != nil {
		return nil, err
	}
	state := "open"
	iss, err := r.Issues.EditIssue(ctx, viewerID(ctx), owner, name, number, domain.IssuePatch{State: &state})
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.ReopenIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// Issue is the resolver for the issue field. A missing issue, or one in a
// repository the actor cannot see, resolves to null rather than an error.
func (r *repositoryResolver) Issue(ctx context.Context, obj *gqlmodel.Repository, number int32) (*gqlmodel.Issue, error) {
	owner, name := splitNWO(obj.NameWithOwner)
	iss, err := r.Resolver.Issues.GetIssue(ctx, viewerID(ctx), owner, name, int64(number))
	if errors.Is(err, domain.ErrIssueNotFound) || errors.Is(err, domain.ErrRepoNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, mapErr(err)
	}
	return r.URLs.GQLIssue(owner, name, iss, r.NodeFormat), nil
}

// Issues is the resolver for the issues field. A repository the actor cannot see
// resolves to an empty connection, never an error, so its existence does not leak.
func (r *repositoryResolver) Issues(ctx context.Context, obj *gqlmodel.Repository, first *int32, after *string, last *int32, before *string, states []gqlmodel.IssueState) (*gqlmodel.IssueConnection, error) {
	page, err := issuePageArgs(first, after, last, before)
	if err != nil {
		return nil, err
	}
	owner, name := splitNWO(obj.NameWithOwner)
	issues, total, err := r.Resolver.Issues.ListIssues(ctx, viewerID(ctx), owner, name, domain.IssueQuery{
		State:     stateFilter(states),
		Sort:      "created",
		Direction: "desc",
		Page:      page.page(),
		PerPage:   page.limit,
	})
	if errors.Is(err, domain.ErrRepoNotFound) {
		return emptyIssueConnection(), nil
	}
	if err != nil {
		return nil, mapErr(err)
	}
	return r.buildIssueConnection(owner, name, issues, total, page.offset), nil
}

// Issue returns generated.IssueResolver implementation.
func (r *Resolver) Issue() generated.IssueResolver { return &issueResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type issueResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
