package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"strings"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/domain"
	"github.com/tamnd/githome/presenter/gqlmodel"
)

// Author is the resolver for the author field. It loads the issue author
// through the per-request user dataloader so that concurrent nested field
// resolutions batch into one user query per request.
func (r *issueResolver) Author(ctx context.Context, obj *gqlmodel.Issue) (gqlmodel.Actor, error) {
	if obj.UserPK == 0 {
		return nil, nil // ghost author
	}
	l := loadersFrom(ctx)
	if l == nil {
		return obj.Author, nil // fallback: loaders not wired (tests)
	}
	u, err := l.Users.Load(ctx, obj.UserPK)
	if err != nil || u == nil {
		return nil, err
	}
	return u, nil
}

// Labels is the resolver for the labels field. It loads the issue's labels
// through the per-request label dataloader so that concurrent nested field
// resolutions batch into one label query per request.
func (r *issueResolver) Labels(ctx context.Context, obj *gqlmodel.Issue, first *int32, after *string) (*gqlmodel.LabelConnection, error) {
	l := loadersFrom(ctx)
	if l == nil {
		return obj.Labels, nil // fallback: loaders not wired (tests)
	}
	nodes, err := l.LabelsByIssue.Load(ctx, obj.PK)
	if err != nil {
		return nil, err
	}
	return &gqlmodel.LabelConnection{Nodes: nodes, PageInfo: &gqlmodel.PageInfo{}, TotalCount: int32(len(nodes))}, nil
}

// Assignees is the resolver for the assignees field. GQLIssue fills the slice
// eagerly, so this resolver returns the pre-loaded connection directly.
func (r *issueResolver) Assignees(ctx context.Context, obj *gqlmodel.Issue, first *int32, after *string) (*gqlmodel.UserConnection, error) {
	if obj.Assignees != nil {
		return obj.Assignees, nil
	}
	return &gqlmodel.UserConnection{}, nil
}

// Milestone is the resolver for the milestone field. GQLIssue fills the
// milestone eagerly, so this resolver returns the pre-loaded value directly.
func (r *issueResolver) Milestone(ctx context.Context, obj *gqlmodel.Issue) (*gqlmodel.Milestone, error) {
	return obj.Milestone, nil
}

// Comments is the resolver for the comments field. It pages the issue's comments
// through the domain on demand, the way gh issue view selects them.
func (r *issueResolver) Comments(ctx context.Context, obj *gqlmodel.Issue, first *int32, after *string, last *int32, before *string) (*gqlmodel.IssueCommentConnection, error) {
	page, err := issuePageArgs(ctx, first, after, last, before)
	if err != nil {
		return nil, err
	}
	total := int32(0)
	if obj.Comments != nil {
		total = obj.Comments.TotalCount
	}
	var comments []*domain.Comment
	start := page.offset
	switch {
	case page.backward:
		var end int
		start, end = page.window(int(total))
		comments, err = r.commentsWindow(ctx, obj.RepoOwner, obj.RepoName, int64(obj.Number), start, end)
	case page.seek > 0:
		// The cursor carries the previous page's last comment id; resume past
		// it with a keyset seek instead of replaying the OFFSET scan.
		comments, err = r.Issues.ListCommentsAfter(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number), page.seek, page.limit)
	case page.offset == 0 && loadersFrom(ctx) != nil:
		// A first-page preview, the shape every node of an issue connection
		// selects. The loader batches all of them into one query; the parent
		// resolution already gated repository visibility, the same trust the
		// label and assignee loaders lean on.
		comments, err = loadersFrom(ctx).CommentsByIssue.Load(ctx, commentsPreviewKey{IssuePK: obj.PK, Limit: page.limit})
		for _, cm := range comments {
			cm.IssueNumber = int64(obj.Number)
		}
	default:
		comments, err = r.Issues.ListComments(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number), int64(page.page()), int64(page.limit))
	}
	if err != nil {
		return nil, mapErr(err)
	}
	nodes := make([]*gqlmodel.IssueComment, 0, len(comments))
	for _, cm := range comments {
		nodes = append(nodes, r.URLs.GQLIssueComment(obj.RepoOwner, obj.RepoName, cm, r.format(ctx)))
	}
	if total < int32(len(nodes)) {
		total = int32(len(nodes))
	}
	var firstID, lastID int64
	if len(comments) > 0 {
		firstID, lastID = comments[0].ID, comments[len(comments)-1].ID
	}
	return &gqlmodel.IssueCommentConnection{
		Nodes:      nodes,
		PageInfo:   pageInfoSeek(start, len(nodes), int(total), firstID, lastID),
		TotalCount: total,
	}, nil
}

// ReactionGroups is the resolver for the reactionGroups field. Githome does not
// track emoji reactions, so this always returns an empty slice.
func (r *issueResolver) ReactionGroups(ctx context.Context, obj *gqlmodel.Issue) ([]*gqlmodel.ReactionGroup, error) {
	return []*gqlmodel.ReactionGroup{}, nil
}

// ProjectCards is the resolver for the projectCards field. Githome does not
// implement classic projects; the connection is always empty.
func (r *issueResolver) ProjectCards(ctx context.Context, obj *gqlmodel.Issue, first *int32, after *string) (*generated.ProjectCardConnection, error) {
	return emptyProjectCardConnection(), nil
}

// ViewerDidAuthor is the resolver for the viewerDidAuthor field. It compares
// the comment author's database key, which the presenter carries off-schema,
// with the request's viewer. An anonymous viewer authored nothing.
func (r *issueCommentResolver) ViewerDidAuthor(ctx context.Context, obj *gqlmodel.IssueComment) (bool, error) {
	v := viewerID(ctx)
	return v != 0 && v == obj.AuthorPK, nil
}

// CreateIssue is the resolver for the createIssue field. It opens an issue on the
// repository named by the input's node ID, attaching the assignees, labels, and
// milestone the input names the way gh issue create sends them.
func (r *mutationResolver) CreateIssue(ctx context.Context, input generated.CreateIssueInput) (*generated.CreateIssuePayload, error) {
	repo, err := r.repoFromID(ctx, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	owner, name := repo.Owner.Login, repo.Name
	in := domain.IssueInput{
		Title: input.Title,
		Body:  input.Body,
	}
	if len(input.LabelIds) > 0 {
		names, lErr := r.labelNamesFromIDs(ctx, input.LabelIds)
		if lErr != nil {
			return nil, lErr
		}
		in.Labels = names
	}
	if len(input.AssigneeIds) > 0 {
		logins, aErr := r.userLoginsFromIDs(ctx, input.AssigneeIds)
		if aErr != nil {
			return nil, aErr
		}
		in.AssigneeLogins = logins
	}
	if input.MilestoneID != nil {
		msNum, mErr := milestoneNumberFromID(*input.MilestoneID)
		if mErr != nil {
			return nil, mErr
		}
		in.MilestoneNumber = &msNum
	}
	iss, err := r.Issues.CreateIssue(ctx, viewerID(ctx), owner, name, in)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.CreateIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// UpdateIssue is the resolver for the updateIssue field. It resolves the issue
// from its node ID and applies the partial patch from the input.
func (r *mutationResolver) UpdateIssue(ctx context.Context, input generated.UpdateIssueInput) (*generated.UpdateIssuePayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	patch := domain.IssuePatch{Title: input.Title, Body: input.Body}
	if input.State != nil {
		s := strings.ToLower(string(*input.State))
		patch.State = &s
	}
	if len(input.LabelIds) > 0 {
		names, lErr := r.labelNamesFromIDs(ctx, input.LabelIds)
		if lErr != nil {
			return nil, lErr
		}
		patch.Labels = &names
	}
	if len(input.AssigneeIds) > 0 {
		logins, aErr := r.userLoginsFromIDs(ctx, input.AssigneeIds)
		if aErr != nil {
			return nil, aErr
		}
		patch.AssigneeLogins = &logins
	}
	if input.MilestoneID != nil {
		msNum, mErr := milestoneNumberFromID(*input.MilestoneID)
		if mErr != nil {
			return nil, mErr
		}
		patch.MilestoneNumber = &msNum
	}
	iss, err := r.Issues.EditIssue(ctx, viewerID(ctx), owner, name, number, patch)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.UpdateIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// AddComment is the resolver for the addComment field. The subject ID is an issue
// node ID; the new comment is returned as a connection edge, the shape gh and the
// GitHub API both render.
func (r *mutationResolver) AddComment(ctx context.Context, input generated.AddCommentInput) (*generated.AddCommentPayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.SubjectID)
	if err != nil {
		return nil, err
	}
	cm, err := r.Issues.CreateComment(ctx, viewerID(ctx), owner, name, number, input.Body)
	if err != nil {
		return nil, mapErr(err)
	}
	node := r.URLs.GQLIssueComment(owner, name, cm, r.format(ctx))
	payload := &generated.AddCommentPayload{
		CommentEdge: &generated.IssueCommentEdge{
			Cursor: encodeCursor(0),
			Node:   node,
		},
		// timelineEdge is the same comment seen as a timeline item.
		TimelineEdge: &gqlmodel.IssueTimelineItemsEdge{
			Cursor: encodeCursor(0),
			Node:   node,
		},
		ClientMutationID: input.ClientMutationID,
	}
	// subject is the issue or pull request that was commented on; resolve it for
	// the few documents that read it back. A lookup failure leaves it null.
	if iss, e := r.Issues.GetIssue(ctx, viewerID(ctx), owner, name, number); e == nil {
		payload.Subject = r.URLs.GQLIssue(owner, name, iss, r.format(ctx))
	}
	return payload, nil
}

// CloseIssue is the resolver for the closeIssue field.
func (r *mutationResolver) CloseIssue(ctx context.Context, input generated.CloseIssueInput) (*generated.CloseIssuePayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.IssueID)
	if err != nil {
		return nil, err
	}
	state := "closed"
	patch := domain.IssuePatch{State: &state}
	if input.StateReason != nil {
		reason := closedStateReason(*input.StateReason)
		patch.StateReason = &reason
	}
	iss, err := r.Issues.EditIssue(ctx, viewerID(ctx), owner, name, number, patch)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.CloseIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// ReopenIssue is the resolver for the reopenIssue field.
func (r *mutationResolver) ReopenIssue(ctx context.Context, input generated.ReopenIssueInput) (*generated.ReopenIssuePayload, error) {
	owner, name, number, err := r.issueRefFromID(ctx, input.IssueID)
	if err != nil {
		return nil, err
	}
	state := "open"
	iss, err := r.Issues.EditIssue(ctx, viewerID(ctx), owner, name, number, domain.IssuePatch{State: &state})
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.ReopenIssuePayload{
		Issue:            r.URLs.GQLIssue(owner, name, iss, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// Issue is the resolver for the issue field. A missing issue, or one in a
// repository the actor cannot see, resolves to null plus a NOT_FOUND error,
// the answer GitHub gives.
func (r *repositoryResolver) Issue(ctx context.Context, obj *gqlmodel.Repository, number int32) (*gqlmodel.Issue, error) {
	owner, name := splitNWO(obj.NameWithOwner)
	iss, err := r.Resolver.Issues.GetIssue(ctx, viewerID(ctx), owner, name, int64(number))
	if errors.Is(err, domain.ErrIssueNotFound) || errors.Is(err, domain.ErrRepoNotFound) {
		return nil, notFoundf("Could not resolve to an Issue with the number of %d.", number)
	}
	if err != nil {
		return nil, mapErr(err)
	}
	return r.URLs.GQLIssue(owner, name, iss, r.format(ctx)), nil
}

// Labels is the resolver for the labels field. The store hands back the whole
// label set in name order, so filtering, reordering, and windowing all happen
// here; label sets are small enough that this stays cheap. A repository the
// actor cannot see resolves to an empty connection, never an error.
func (r *repositoryResolver) Labels(ctx context.Context, obj *gqlmodel.Repository, first *int32, after *string, last *int32, before *string, orderBy *generated.LabelOrder, query *string) (*gqlmodel.LabelConnection, error) {
	page, err := issuePageArgs(ctx, first, after, last, before)
	if err != nil {
		return nil, err
	}
	owner, name := splitNWO(obj.NameWithOwner)
	labels, err := r.Resolver.Issues.ListLabels(ctx, viewerID(ctx), owner, name)
	if errors.Is(err, domain.ErrRepoNotFound) {
		return &gqlmodel.LabelConnection{Nodes: []*gqlmodel.Label{}, PageInfo: &gqlmodel.PageInfo{}}, nil
	}
	if err != nil {
		return nil, mapErr(err)
	}
	if query != nil && *query != "" {
		q := strings.ToLower(*query)
		kept := labels[:0]
		for _, l := range labels {
			if strings.Contains(strings.ToLower(l.Name), q) {
				kept = append(kept, l)
			}
		}
		labels = kept
	}
	sortLabels(labels, orderBy)
	total := len(labels)
	start, end := page.window(total)
	nodes := make([]*gqlmodel.Label, 0, end-start)
	edges := make([]*gqlmodel.LabelEdge, 0, end-start)
	for _, l := range labels[start:end] {
		n := r.URLs.GQLLabel(owner, name, l, r.format(ctx))
		nodes = append(nodes, n)
		edges = append(edges, &gqlmodel.LabelEdge{Cursor: n.ID, Node: n})
	}
	return &gqlmodel.LabelConnection{
		Edges:      edges,
		Nodes:      nodes,
		PageInfo:   pageInfoFor(start, end-start, total),
		TotalCount: int32(total),
	}, nil
}

// Issues is the resolver for the issues field. A repository the actor cannot see
// resolves to an empty connection, never an error, so its existence does not leak.
func (r *repositoryResolver) Issues(ctx context.Context, obj *gqlmodel.Repository, first *int32, after *string, last *int32, before *string, states []gqlmodel.IssueState, filterBy *generated.IssueFilters, orderBy *generated.IssueOrder, labels []string) (*gqlmodel.IssueConnection, error) {
	page, err := issuePageArgs(ctx, first, after, last, before)
	if err != nil {
		return nil, err
	}
	if page.backward {
		return nil, gqlError{"backward pagination with `last`/`before` is not supported on this connection."}
	}
	owner, name := splitNWO(obj.NameWithOwner)
	q := issueListQuery(states, filterBy, orderBy, labels, page)

	// The first page and any cursor carrying a seek key take the keyset path:
	// the page is an index range read, hasNextPage comes from the limit+1
	// probe, and the COUNT runs only when totalCount is actually selected.
	// Legacy offset-only cursors keep the page-number path.
	if page.seek > 0 || page.offset == 0 {
		q.AfterNumber = page.seek
		issues, hasMore, err := r.Resolver.Issues.ListIssuesPage(ctx, viewerID(ctx), owner, name, q)
		if errors.Is(err, domain.ErrRepoNotFound) {
			return emptyIssueConnection(), nil
		}
		if err != nil {
			return nil, mapErr(err)
		}
		total := lazyTotal(page.offset, len(issues), hasMore)
		if totalCountSelected(ctx) {
			if total, err = r.Resolver.Issues.CountIssues(ctx, viewerID(ctx), owner, name, q); err != nil {
				return nil, mapErr(err)
			}
		}
		return r.buildIssueConnection(ctx, owner, name, issues, total, page.offset), nil
	}

	issues, total, err := r.Resolver.Issues.ListIssues(ctx, viewerID(ctx), owner, name, q)
	if errors.Is(err, domain.ErrRepoNotFound) {
		return emptyIssueConnection(), nil
	}
	if err != nil {
		return nil, mapErr(err)
	}
	return r.buildIssueConnection(ctx, owner, name, issues, total, page.offset), nil
}

// Issue returns generated.IssueResolver implementation.
func (r *Resolver) Issue() generated.IssueResolver { return &issueResolver{r} }

// IssueComment returns generated.IssueCommentResolver implementation.
func (r *Resolver) IssueComment() generated.IssueCommentResolver { return &issueCommentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type issueResolver struct{ *Resolver }
type issueCommentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
