package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/tamnd/githome/api/graphql/generated"
)

// AddLabelsToLabelable is the resolver for the addLabelsToLabelable field. gh
// issue edit --add-label and gh pr edit --add-label send this mutation.
func (r *mutationResolver) AddLabelsToLabelable(ctx context.Context, input generated.AddLabelsToLabelableInput) (*generated.AddLabelsToLabelablePayload, error) {
	owner, name, number, isPR, err := r.labelableRefFromID(ctx, input.LabelableID)
	if err != nil {
		return nil, err
	}
	names, err := r.labelNamesFromIDs(ctx, input.LabelIds)
	if err != nil {
		return nil, err
	}
	iss, err := r.Issues.AddLabels(ctx, viewerID(ctx), owner, name, number, names)
	if err != nil {
		return nil, mapErr(err)
	}
	labelable, lErr := r.labelableFromIssue(ctx, owner, name, number, isPR, iss)
	if lErr != nil {
		return nil, lErr
	}
	return &generated.AddLabelsToLabelablePayload{
		Labelable:        labelable,
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// RemoveLabelsFromLabelable is the resolver for the removeLabelsFromLabelable
// field. gh issue edit --remove-label and gh pr edit --remove-label send this
// mutation.
func (r *mutationResolver) RemoveLabelsFromLabelable(ctx context.Context, input generated.RemoveLabelsFromLabelableInput) (*generated.RemoveLabelsFromLabelablePayload, error) {
	owner, name, number, isPR, err := r.labelableRefFromID(ctx, input.LabelableID)
	if err != nil {
		return nil, err
	}
	names, err := r.labelNamesFromIDs(ctx, input.LabelIds)
	if err != nil {
		return nil, err
	}
	iss, err := r.Issues.RemoveLabels(ctx, viewerID(ctx), owner, name, number, names)
	if err != nil {
		return nil, mapErr(err)
	}
	labelable, lErr := r.labelableFromIssue(ctx, owner, name, number, isPR, iss)
	if lErr != nil {
		return nil, lErr
	}
	return &generated.RemoveLabelsFromLabelablePayload{
		Labelable:        labelable,
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// AddAssigneesToAssignable is the resolver for the addAssigneesToAssignable
// field. gh issue edit --add-assignee and gh pr edit --add-assignee send this
// mutation.
func (r *mutationResolver) AddAssigneesToAssignable(ctx context.Context, input generated.AddAssigneesToAssignableInput) (*generated.AddAssigneesToAssignablePayload, error) {
	owner, name, number, isPR, err := r.labelableRefFromID(ctx, input.AssignableID)
	if err != nil {
		return nil, err
	}
	logins, err := r.userLoginsFromIDs(ctx, input.AssigneeIds)
	if err != nil {
		return nil, err
	}
	iss, err := r.Issues.AddAssignees(ctx, viewerID(ctx), owner, name, number, logins)
	if err != nil {
		return nil, mapErr(err)
	}
	assignable, aErr := r.assignableFromIssue(ctx, owner, name, number, isPR, iss)
	if aErr != nil {
		return nil, aErr
	}
	return &generated.AddAssigneesToAssignablePayload{
		Assignable:       assignable,
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// RemoveAssigneesFromAssignable is the resolver for the
// removeAssigneesFromAssignable field. gh issue edit --remove-assignee and gh
// pr edit --remove-assignee send this mutation.
func (r *mutationResolver) RemoveAssigneesFromAssignable(ctx context.Context, input generated.RemoveAssigneesFromAssignableInput) (*generated.RemoveAssigneesFromAssignablePayload, error) {
	owner, name, number, isPR, err := r.labelableRefFromID(ctx, input.AssignableID)
	if err != nil {
		return nil, err
	}
	logins, err := r.userLoginsFromIDs(ctx, input.AssigneeIds)
	if err != nil {
		return nil, err
	}
	iss, err := r.Issues.RemoveAssignees(ctx, viewerID(ctx), owner, name, number, logins)
	if err != nil {
		return nil, mapErr(err)
	}
	assignable, aErr := r.assignableFromIssue(ctx, owner, name, number, isPR, iss)
	if aErr != nil {
		return nil, aErr
	}
	return &generated.RemoveAssigneesFromAssignablePayload{
		Assignable:       assignable,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
