package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/domain"
	"github.com/tamnd/githome/git"
	"github.com/tamnd/githome/presenter/gqlmodel"
)

// CreatePullRequest is the resolver for the createPullRequest field. gh pr create
// sends this mutation with the repository node ID, base/head branch names, title,
// and optional body and draft flag.
func (r *mutationResolver) CreatePullRequest(ctx context.Context, input generated.CreatePullRequestInput) (*generated.CreatePullRequestPayload, error) {
	repo, err := r.repoFromID(ctx, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	owner, name := repo.Owner.Login, repo.Name
	draft := false
	if input.Draft != nil {
		draft = *input.Draft
	}
	mcm := false
	if input.MaintainerCanModify != nil {
		mcm = *input.MaintainerCanModify
	}
	pr, err := r.Pulls.CreatePR(ctx, viewerID(ctx), owner, name, domain.PRInput{
		Title:               input.Title,
		Body:                input.Body,
		Base:                input.BaseRefName,
		Head:                input.HeadRefName,
		Draft:               draft,
		MaintainerCanModify: mcm,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.CreatePullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// MergePullRequest is the resolver for the mergePullRequest field. gh pr merge
// sends this mutation with the pull request node ID and optional merge method.
func (r *mutationResolver) MergePullRequest(ctx context.Context, input generated.MergePullRequestInput) (*generated.MergePullRequestPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	mi := domain.MergeInput{Method: git.MergeCommit}
	if input.MergeMethod != nil {
		switch *input.MergeMethod {
		case gqlmodel.PullRequestMergeMethodSquash:
			mi.Method = git.MergeSquash
		case gqlmodel.PullRequestMergeMethodRebase:
			mi.Method = git.MergeRebase
		}
	}
	if input.CommitHeadline != nil {
		mi.CommitTitle = *input.CommitHeadline
	}
	if input.CommitBody != nil {
		mi.CommitMessage = *input.CommitBody
	}
	if input.ExpectedHeadOid != nil {
		mi.ExpectedHead = string(*input.ExpectedHeadOid)
	}
	if _, err := r.Pulls.Merge(ctx, viewerID(ctx), owner, name, number, mi); err != nil {
		return nil, mapMergeErr(err)
	}
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.MergePullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// EnablePullRequestAutoMerge is the resolver for the enablePullRequestAutoMerge
// field. Githome does not implement auto-merge; this stub succeeds and returns
// the pull request unchanged so gh pr merge --auto does not hard-fail.
func (r *mutationResolver) EnablePullRequestAutoMerge(ctx context.Context, input generated.EnablePullRequestAutoMergeInput) (*generated.EnablePullRequestAutoMergePayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.EnablePullRequestAutoMergePayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// UpdatePullRequest is the resolver for the updatePullRequest field. gh pr edit
// sends this mutation to change the title, body, or base branch.
func (r *mutationResolver) UpdatePullRequest(ctx context.Context, input generated.UpdatePullRequestInput) (*generated.UpdatePullRequestPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	patch := domain.PRPatch{
		Title:               input.Title,
		Body:                input.Body,
		BaseRef:             input.BaseRefName,
		MaintainerCanModify: input.MaintainerCanModify,
	}
	if len(input.LabelIds) > 0 {
		names, lErr := r.labelNamesFromIDs(ctx, input.LabelIds)
		if lErr != nil {
			return nil, lErr
		}
		patch.Labels = &names
	} else if input.LabelIds != nil {
		empty := []string{}
		patch.Labels = &empty
	}
	if len(input.AssigneeIds) > 0 {
		logins, aErr := r.userLoginsFromIDs(ctx, input.AssigneeIds)
		if aErr != nil {
			return nil, aErr
		}
		patch.AssigneeLogins = &logins
	} else if input.AssigneeIds != nil {
		empty := []string{}
		patch.AssigneeLogins = &empty
	}
	pr, err := r.Pulls.UpdatePR(ctx, viewerID(ctx), owner, name, number, patch)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.UpdatePullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// RequestReviews is the resolver for the requestReviews field. Githome does not
// yet track review requests; this stub succeeds and returns the pull request
// unchanged so gh pr edit --reviewer does not hard-fail.
func (r *mutationResolver) RequestReviews(ctx context.Context, input generated.RequestReviewsInput) (*generated.RequestReviewsPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.RequestReviewsPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// ConvertPullRequestToDraft marks a pull request as a draft.
func (r *mutationResolver) ConvertPullRequestToDraft(ctx context.Context, input generated.ConvertPullRequestToDraftInput) (*generated.ConvertPullRequestToDraftPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.SetDraft(ctx, viewerID(ctx), owner, name, number, true)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.ConvertPullRequestToDraftPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// MarkPullRequestReadyForReview removes the draft status from a pull request.
func (r *mutationResolver) MarkPullRequestReadyForReview(ctx context.Context, input generated.MarkPullRequestReadyForReviewInput) (*generated.MarkPullRequestReadyForReviewPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.SetDraft(ctx, viewerID(ctx), owner, name, number, false)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.MarkPullRequestReadyForReviewPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// DisablePullRequestAutoMerge is the resolver for the disablePullRequestAutoMerge
// field. Githome does not support auto-merge, so this is a no-op that returns
// the pull request as-is.
func (r *mutationResolver) DisablePullRequestAutoMerge(ctx context.Context, input generated.DisablePullRequestAutoMergeInput) (*generated.DisablePullRequestAutoMergePayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.DisablePullRequestAutoMergePayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// BaseRef returns the base branch ref of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) BaseRef(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Ref, error) {
	return obj.BaseRef, nil
}

// HeadRef returns the head branch ref of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) HeadRef(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Ref, error) {
	return obj.HeadRef, nil
}

// Labels returns the labels of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) Labels(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*gqlmodel.LabelConnection, error) {
	if obj.Labels != nil {
		return obj.Labels, nil
	}
	return &gqlmodel.LabelConnection{}, nil
}

// Assignees returns the assignees of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) Assignees(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*gqlmodel.UserConnection, error) {
	if obj.Assignees != nil {
		return obj.Assignees, nil
	}
	return &gqlmodel.UserConnection{}, nil
}

// Milestone returns the milestone of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) Milestone(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Milestone, error) {
	return obj.Milestone, nil
}

// AutoMergeRequest is the resolver for the autoMergeRequest field. Githome does
// not persist auto-merge configuration; this always returns null.
func (r *pullRequestResolver) AutoMergeRequest(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.AutoMergeRequest, error) {
	return nil, nil
}

// Commits is the resolver for the commits field. It reads the pull request's own
// commits through the git layer on demand, the way gh pr view selects them.
func (r *pullRequestResolver) Commits(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string, last *int32, before *string) (*gqlmodel.PullRequestCommitConnection, error) {
	page, err := issuePageArgs(first, after, last, before)
	if err != nil {
		return nil, err
	}
	commits, err := r.Pulls.Commits(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	total := len(commits)
	start, end := page.window(total)
	nodes := make([]*gqlmodel.PullRequestCommit, 0, end-start)
	for _, cm := range commits[start:end] {
		nodes = append(nodes, r.URLs.GQLPullRequestCommit(obj.RepoOwner, obj.RepoName, cm))
	}
	return &gqlmodel.PullRequestCommitConnection{Nodes: nodes, TotalCount: int32(total)}, nil
}

// Files is the resolver for the files field. It reads the per-file diff of the
// pull request range through the git layer on demand.
func (r *pullRequestResolver) Files(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*gqlmodel.PullRequestChangedFileConnection, error) {
	if _, err := issuePageArgs(first, after, nil, nil); err != nil {
		return nil, err
	}
	files, err := r.Pulls.Files(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	nodes := make([]*gqlmodel.PullRequestChangedFile, 0, len(files))
	for _, f := range files {
		nodes = append(nodes, r.URLs.GQLPullRequestChangedFile(f))
	}
	return &gqlmodel.PullRequestChangedFileConnection{Nodes: nodes, TotalCount: int32(len(nodes))}, nil
}

// Reviews is the resolver for the reviews field. It reads the pull request's
// submitted reviews through the review service on demand.
func (r *pullRequestResolver) Reviews(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*generated.PullRequestReviewConnection, error) {
	if _, err := issuePageArgs(first, after, nil, nil); err != nil {
		return nil, err
	}
	revs, err := r.Resolver.Reviews.ListReviews(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	nodes := make([]*generated.PullRequestReview, 0, len(revs))
	for _, rv := range revs {
		nodes = append(nodes, gqlReview(rv, r.URLs, obj.RepoOwner, obj.RepoName, r.NodeFormat))
	}
	return &generated.PullRequestReviewConnection{Nodes: nodes, TotalCount: int32(len(nodes))}, nil
}

// ReviewRequests is the resolver for the reviewRequests field. Githome does not
// persist review requests in a separate table; this returns an empty connection
// so VS Code and other clients that select the field do not error.
func (r *pullRequestResolver) ReviewRequests(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*generated.ReviewRequestConnection, error) {
	return &generated.ReviewRequestConnection{Nodes: []*generated.ReviewRequest{}, TotalCount: 0}, nil
}

// Comments is the resolver for the comments field on PullRequest. It reads the
// pull request's issue-level comments through the issue service; not inline review
// comments, which are under reviewThreads.
func (r *pullRequestResolver) Comments(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string, last *int32, before *string) (*gqlmodel.IssueCommentConnection, error) {
	page, err := issuePageArgs(first, after, last, before)
	if err != nil {
		return nil, err
	}
	total := obj.CommentsCount
	var comments []*domain.Comment
	if page.backward {
		start, end := page.window(int(total))
		comments, err = r.commentsWindow(ctx, obj.RepoOwner, obj.RepoName, int64(obj.Number), start, end)
	} else {
		comments, err = r.Issues.ListComments(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number), int64(page.page()), int64(page.limit))
	}
	if err != nil {
		return nil, mapErr(err)
	}
	nodes := make([]*gqlmodel.IssueComment, 0, len(comments))
	for _, cm := range comments {
		nodes = append(nodes, r.URLs.GQLIssueComment(obj.RepoOwner, obj.RepoName, cm, r.NodeFormat))
	}
	if total < int32(len(nodes)) {
		total = int32(len(nodes))
	}
	return &gqlmodel.IssueCommentConnection{Nodes: nodes, TotalCount: total}, nil
}

// PullRequest is the resolver for the pullRequest field. A missing pull request,
// or one in a repository the actor cannot see, resolves to null rather than an
// error.
func (r *repositoryResolver) PullRequest(ctx context.Context, obj *gqlmodel.Repository, number int32) (*gqlmodel.PullRequest, error) {
	owner, name := splitNWO(obj.NameWithOwner)
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, int64(number))
	if errors.Is(err, domain.ErrPullNotFound) || errors.Is(err, domain.ErrRepoNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, mapErr(err)
	}
	return r.URLs.GQLPullRequest(owner, name, pr, r.NodeFormat), nil
}

// PullRequests is the resolver for the pullRequests field. A repository the actor
// cannot see resolves to an empty connection, never an error, so its existence
// does not leak.
func (r *repositoryResolver) PullRequests(ctx context.Context, obj *gqlmodel.Repository, first *int32, after *string, last *int32, before *string, states []gqlmodel.PullRequestState) (*gqlmodel.PullRequestConnection, error) {
	page, err := issuePageArgs(first, after, last, before)
	if err != nil {
		return nil, err
	}
	owner, name := splitNWO(obj.NameWithOwner)
	prs, total, err := r.Pulls.ListPRs(ctx, viewerID(ctx), owner, name, domain.PRQuery{
		State:   pullStateFilter(states),
		Page:    page.page(),
		PerPage: page.limit,
	})
	if errors.Is(err, domain.ErrRepoNotFound) {
		return emptyPullRequestConnection(), nil
	}
	if err != nil {
		return nil, mapErr(err)
	}
	return r.buildPullRequestConnection(owner, name, prs, total, page.offset), nil
}

// Commit returns generated.CommitResolver implementation.
func (r *Resolver) Commit() generated.CommitResolver { return &commitResolver{r} }

// PullRequest returns generated.PullRequestResolver implementation.
func (r *Resolver) PullRequest() generated.PullRequestResolver { return &pullRequestResolver{r} }

type commitResolver struct{ *Resolver }
type pullRequestResolver struct{ *Resolver }
