package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"strings"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/domain"
	"github.com/tamnd/githome/git"
	"github.com/tamnd/githome/nodeid"
	"github.com/tamnd/githome/presenter"
	"github.com/tamnd/githome/presenter/gqlmodel"
)

// ID is the resolver for the Commit id field. The node id is the repo-scoped
// commit encoding, which needs the repository's database id; the presenter
// fills it where it has one, and this resolver looks the repository up by the
// coordinates the commit carries otherwise.
func (r *commitResolver) ID(ctx context.Context, obj *gqlmodel.Commit) (string, error) {
	if obj.ID != "" {
		return obj.ID, nil
	}
	repo, err := r.Repos.GetRepo(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName)
	if err != nil {
		return "", mapErr(err)
	}
	return nodeid.EncodeGitObject("commit", repo.ID, string(obj.Oid)), nil
}

// Message is the resolver for the Commit message field. The presenter fills
// the message where it already read the commit; a Ref.target commit starts
// out as just a SHA, so the resolver reads the commit from git on demand.
func (r *commitResolver) Message(ctx context.Context, obj *gqlmodel.Commit) (string, error) {
	if obj.Message != "" {
		return obj.Message, nil
	}
	c, ok, err := r.loadCommit(ctx, obj)
	if err != nil || !ok {
		return "", err
	}
	return c.Message, nil
}

// MessageHeadline is the resolver for the Commit messageHeadline field,
// loading the commit on demand the way message does.
func (r *commitResolver) MessageHeadline(ctx context.Context, obj *gqlmodel.Commit) (string, error) {
	if obj.MessageHeadline != "" {
		return obj.MessageHeadline, nil
	}
	msg, err := r.Message(ctx, obj)
	if err != nil {
		return "", err
	}
	if i := strings.IndexByte(msg, '\n'); i >= 0 {
		return msg[:i], nil
	}
	return msg, nil
}

// CreatePullRequest is the resolver for the createPullRequest field. gh pr create
// sends this mutation with the repository node ID, base/head branch names, title,
// and optional body and draft flag.
func (r *mutationResolver) CreatePullRequest(ctx context.Context, input generated.CreatePullRequestInput) (*generated.CreatePullRequestPayload, error) {
	repo, err := r.repoFromID(ctx, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	owner, name := repo.Owner.Login, repo.Name
	draft := false
	if input.Draft != nil {
		draft = *input.Draft
	}
	mcm := false
	if input.MaintainerCanModify != nil {
		mcm = *input.MaintainerCanModify
	}
	pr, err := r.Pulls.CreatePR(ctx, viewerID(ctx), owner, name, domain.PRInput{
		Title:               input.Title,
		Body:                input.Body,
		Base:                input.BaseRefName,
		Head:                input.HeadRefName,
		Draft:               draft,
		MaintainerCanModify: mcm,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.CreatePullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// MergePullRequest is the resolver for the mergePullRequest field. gh pr merge
// sends this mutation with the pull request node ID and optional merge method.
func (r *mutationResolver) MergePullRequest(ctx context.Context, input generated.MergePullRequestInput) (*generated.MergePullRequestPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	mi := domain.MergeInput{Method: git.MergeCommit}
	if input.MergeMethod != nil {
		switch *input.MergeMethod {
		case gqlmodel.PullRequestMergeMethodSquash:
			mi.Method = git.MergeSquash
		case gqlmodel.PullRequestMergeMethodRebase:
			mi.Method = git.MergeRebase
		}
	}
	if input.CommitHeadline != nil {
		mi.CommitTitle = *input.CommitHeadline
	}
	if input.CommitBody != nil {
		mi.CommitMessage = *input.CommitBody
	}
	if input.ExpectedHeadOid != nil {
		mi.ExpectedHead = string(*input.ExpectedHeadOid)
	}
	if _, err := r.Pulls.Merge(ctx, viewerID(ctx), owner, name, number, mi); err != nil {
		return nil, mapMergeErr(err)
	}
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.MergePullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// EnablePullRequestAutoMerge is the resolver for the enablePullRequestAutoMerge
// field. Githome does not implement auto-merge, so rather than report success
// for a change it never makes — leaving gh pr merge --auto believing the pull
// request will merge itself — it returns the UNPROCESSABLE error GitHub returns
// when auto-merge cannot be enabled. It still validates the pull request id so
// a bad id reports NOT_FOUND, matching the order GitHub checks.
func (r *mutationResolver) EnablePullRequestAutoMerge(ctx context.Context, input generated.EnablePullRequestAutoMergeInput) (*generated.EnablePullRequestAutoMergePayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	if _, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number); err != nil {
		return nil, mapErr(err)
	}
	return nil, unprocessablef("Auto-merge is not available for this repository.")
}

// UpdatePullRequest is the resolver for the updatePullRequest field. gh pr edit
// sends this mutation to change the title, body, or base branch.
func (r *mutationResolver) UpdatePullRequest(ctx context.Context, input generated.UpdatePullRequestInput) (*generated.UpdatePullRequestPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	patch := domain.PRPatch{
		Title:               input.Title,
		Body:                input.Body,
		BaseRef:             input.BaseRefName,
		MaintainerCanModify: input.MaintainerCanModify,
	}
	if len(input.LabelIds) > 0 {
		names, lErr := r.labelNamesFromIDs(ctx, input.LabelIds)
		if lErr != nil {
			return nil, lErr
		}
		patch.Labels = &names
	} else if input.LabelIds != nil {
		empty := []string{}
		patch.Labels = &empty
	}
	if len(input.AssigneeIds) > 0 {
		logins, aErr := r.userLoginsFromIDs(ctx, input.AssigneeIds)
		if aErr != nil {
			return nil, aErr
		}
		patch.AssigneeLogins = &logins
	} else if input.AssigneeIds != nil {
		empty := []string{}
		patch.AssigneeLogins = &empty
	}
	pr, err := r.Pulls.UpdatePR(ctx, viewerID(ctx), owner, name, number, patch)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.UpdatePullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// ClosePullRequest is the resolver for the closePullRequest field. It closes
// the pull request without merging, the mutation gh pr close sends.
func (r *mutationResolver) ClosePullRequest(ctx context.Context, input generated.ClosePullRequestInput) (*generated.ClosePullRequestPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	state := "closed"
	pr, err := r.Pulls.UpdatePR(ctx, viewerID(ctx), owner, name, number, domain.PRPatch{State: &state})
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.ClosePullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// ReopenPullRequest is the resolver for the reopenPullRequest field. It reopens
// a closed, unmerged pull request, the mutation gh pr reopen sends.
func (r *mutationResolver) ReopenPullRequest(ctx context.Context, input generated.ReopenPullRequestInput) (*generated.ReopenPullRequestPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	state := "open"
	pr, err := r.Pulls.UpdatePR(ctx, viewerID(ctx), owner, name, number, domain.PRPatch{State: &state})
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.ReopenPullRequestPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// RequestReviews is the resolver for the requestReviews field. gh pr create
// --reviewer and gh pr edit --add-reviewer send it. It persists the requested
// reviewers through the pull service rather than reporting a hollow success.
// union defaults to false, which GitHub treats as replacing the current set, so
// reviewers no longer named are dropped first; union: true adds without
// removing.
func (r *mutationResolver) RequestReviews(ctx context.Context, input generated.RequestReviewsInput) (*generated.RequestReviewsPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	logins, lErr := r.userLoginsFromIDs(ctx, input.UserIds)
	if lErr != nil {
		return nil, lErr
	}
	viewer := viewerID(ctx)
	if input.Union == nil || !*input.Union {
		current, gErr := r.Pulls.GetPR(ctx, viewer, owner, name, number)
		if gErr != nil {
			return nil, mapErr(gErr)
		}
		want := make(map[string]bool, len(logins))
		for _, l := range logins {
			want[l] = true
		}
		var stale []string
		for _, u := range current.RequestedReviewers {
			if !want[u.Login] {
				stale = append(stale, u.Login)
			}
		}
		if len(stale) > 0 {
			if _, rErr := r.Pulls.RemoveRequestedReviewers(ctx, viewer, owner, name, number, stale); rErr != nil {
				return nil, mapErr(rErr)
			}
		}
	}
	pr, err := r.Pulls.RequestReviewers(ctx, viewer, owner, name, number, logins)
	if err != nil {
		return nil, mapErr(err)
	}
	payload := &generated.RequestReviewsPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}
	// requestedReviewersEdge is the first newly requested reviewer as an edge so
	// a client can splice it into a cached connection. It comes from the
	// refreshed pull request's reviewer set, so no extra lookup is needed.
	if len(logins) > 0 {
		for _, u := range pr.RequestedReviewers {
			if u.Login == logins[0] {
				payload.RequestedReviewersEdge = &gqlmodel.UserEdge{
					Cursor: encodeCursor(0),
					Node:   r.URLs.GQLUser(u, r.format(ctx)),
				}
				break
			}
		}
	}
	return payload, nil
}

// ConvertPullRequestToDraft marks a pull request as a draft.
func (r *mutationResolver) ConvertPullRequestToDraft(ctx context.Context, input generated.ConvertPullRequestToDraftInput) (*generated.ConvertPullRequestToDraftPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.SetDraft(ctx, viewerID(ctx), owner, name, number, true)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.ConvertPullRequestToDraftPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// MarkPullRequestReadyForReview removes the draft status from a pull request.
func (r *mutationResolver) MarkPullRequestReadyForReview(ctx context.Context, input generated.MarkPullRequestReadyForReviewInput) (*generated.MarkPullRequestReadyForReviewPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.SetDraft(ctx, viewerID(ctx), owner, name, number, false)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.MarkPullRequestReadyForReviewPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// DisablePullRequestAutoMerge is the resolver for the disablePullRequestAutoMerge
// field. Githome does not support auto-merge, so this is a no-op that returns
// the pull request as-is.
func (r *mutationResolver) DisablePullRequestAutoMerge(ctx context.Context, input generated.DisablePullRequestAutoMergeInput) (*generated.DisablePullRequestAutoMergePayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.DisablePullRequestAutoMergePayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// UpdatePullRequestBranch is the resolver for the updatePullRequestBranch field.
// gh pr update-branch sends it to merge the base branch into the head branch.
// expectedHeadOid, when supplied, guards against updating a branch that moved
// since the client last read it, matching GitHub's optimistic check.
func (r *mutationResolver) UpdatePullRequestBranch(ctx context.Context, input generated.UpdatePullRequestBranchInput) (*generated.UpdatePullRequestBranchPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	expected := ""
	if input.ExpectedHeadOid != nil {
		expected = string(*input.ExpectedHeadOid)
	}
	if err := r.Pulls.UpdateBranch(ctx, viewerID(ctx), owner, name, number, expected); err != nil {
		return nil, mapMergeErr(err)
	}
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, number)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.UpdatePullRequestBranchPayload{
		PullRequest:      r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// AvatarURL is the resolver for the avatarUrl field on Organization. It applies
// the optional size the same way the User resolver does. Githome does not model
// organizations, so this only runs if a future caller hands one to the schema.
func (r *organizationResolver) AvatarURL(ctx context.Context, obj *gqlmodel.Organization, size *int32) (gqlmodel.URI, error) {
	return avatarWithSize(obj.AvatarURL, size), nil
}

// Repositories is the resolver for the repositories field on Organization.
// Githome does not model organizations or their repositories, so the connection
// is always empty, never null.
func (r *organizationResolver) Repositories(ctx context.Context, obj *gqlmodel.Organization, first *int32, after *string, ownerAffiliations []generated.RepositoryAffiliation, isArchived *bool, isFork *bool, privacy *generated.RepositoryPrivacy, orderBy *generated.RepositoryOrder) (*gqlmodel.RepositoryConnection, error) {
	return &gqlmodel.RepositoryConnection{Nodes: []*gqlmodel.Repository{}, PageInfo: &gqlmodel.PageInfo{}}, nil
}

// BaseRef returns the base branch ref of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) BaseRef(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Ref, error) {
	return obj.BaseRef, nil
}

// HeadRef returns the head branch ref of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) HeadRef(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Ref, error) {
	return obj.HeadRef, nil
}

// MergeCommit is the resolver for the mergeCommit field. It resolves the merge
// commit from its recorded sha once the pull request has merged, returning null
// while it is open or when the commit is no longer reachable.
func (r *pullRequestResolver) MergeCommit(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Commit, error) {
	if !obj.Merged || obj.MergeCommitOID == "" {
		return nil, nil
	}
	repo, err := r.Resolver.Repos.GetRepo(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName)
	if err != nil {
		return nil, mapErr(err)
	}
	c, err := r.Resolver.Repos.GetCommit(repo, obj.MergeCommitOID)
	if err != nil {
		return nil, nil
	}
	return presenter.GQLCommit(repo.ID, repo.Owner.Login, repo.Name, c), nil
}

// PotentialMergeCommit is the resolver for the potentialMergeCommit field.
// GitHub computes a test-merge commit for an open, mergeable pull request;
// Githome does not, so it returns null — a value GitHub itself returns whenever
// the test merge has not been computed.
func (r *pullRequestResolver) PotentialMergeCommit(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Commit, error) {
	return nil, nil
}

// ClosingIssuesReferences is the resolver for the closingIssuesReferences field.
// It parses the body for closing keywords and resolves each referenced issue,
// dropping references that do not name a visible issue, the way GitHub omits a
// reference it cannot link.
func (r *pullRequestResolver) ClosingIssuesReferences(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string, last *int32, before *string, orderBy *generated.IssueOrder) (*gqlmodel.IssueConnection, error) {
	page, err := issuePageArgs(ctx, first, after, last, before)
	if err != nil {
		return nil, err
	}
	viewer := viewerID(ctx)
	issues := make([]*domain.Issue, 0)
	for _, n := range closingIssueNumbers(obj.Body) {
		iss, err := r.Resolver.Issues.GetIssue(ctx, viewer, obj.RepoOwner, obj.RepoName, n)
		if err != nil {
			continue
		}
		issues = append(issues, iss)
	}
	total := len(issues)
	start, end := page.window(total)
	return r.buildIssueConnection(ctx, obj.RepoOwner, obj.RepoName, issues[start:end], total, start), nil
}

// Labels returns the labels of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) Labels(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*gqlmodel.LabelConnection, error) {
	if obj.Labels != nil {
		return obj.Labels, nil
	}
	return &gqlmodel.LabelConnection{PageInfo: &gqlmodel.PageInfo{}}, nil
}

// Assignees returns the assignees of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) Assignees(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*gqlmodel.UserConnection, error) {
	if obj.Assignees != nil {
		return obj.Assignees, nil
	}
	return &gqlmodel.UserConnection{}, nil
}

// Milestone returns the milestone of the pull request, pre-loaded by the presenter.
func (r *pullRequestResolver) Milestone(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.Milestone, error) {
	return obj.Milestone, nil
}

// AutoMergeRequest is the resolver for the autoMergeRequest field. Githome does
// not persist auto-merge configuration; this always returns null.
func (r *pullRequestResolver) AutoMergeRequest(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.AutoMergeRequest, error) {
	return nil, nil
}

// Commits is the resolver for the commits field. It reads the pull request's own
// commits through the git layer on demand, the way gh pr view selects them.
func (r *pullRequestResolver) Commits(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string, last *int32, before *string) (*gqlmodel.PullRequestCommitConnection, error) {
	page, err := issuePageArgs(ctx, first, after, last, before)
	if err != nil {
		return nil, err
	}
	// A count-only selection answers from the commits_count column the
	// mergeability recompute maintains, the same source the additions and
	// changedFiles fields read, so a 30-node connection selecting
	// commits { totalCount } forks no git processes.
	if countOnlySelection(ctx) {
		total := int(obj.CommitsCount)
		start, end := page.window(total)
		return &gqlmodel.PullRequestCommitConnection{
			Nodes:      []*gqlmodel.PullRequestCommit{},
			PageInfo:   pageInfoFor(start, end-start, total),
			TotalCount: int32(total),
		}, nil
	}
	commits, err := r.Pulls.Commits(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	total := len(commits)
	start, end := page.window(total)
	nodes := make([]*gqlmodel.PullRequestCommit, 0, end-start)
	for _, cm := range commits[start:end] {
		nodes = append(nodes, r.URLs.GQLPullRequestCommit(obj.RepoOwner, obj.RepoName, cm))
	}
	return &gqlmodel.PullRequestCommitConnection{
		Nodes:      nodes,
		PageInfo:   pageInfoFor(start, end-start, total),
		TotalCount: int32(total),
	}, nil
}

// Files is the resolver for the files field. It reads the per-file diff of the
// pull request range through the git layer on demand.
func (r *pullRequestResolver) Files(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*gqlmodel.PullRequestChangedFileConnection, error) {
	page, err := issuePageArgs(ctx, first, after, nil, nil)
	if err != nil {
		return nil, err
	}
	// Count-only selections read the changed_files column, exactly what the
	// changedFiles schema field reports, instead of re-diffing the range.
	if countOnlySelection(ctx) {
		total := int(obj.ChangedFiles)
		start, end := page.window(total)
		return &gqlmodel.PullRequestChangedFileConnection{
			Nodes:      []*gqlmodel.PullRequestChangedFile{},
			PageInfo:   pageInfoFor(start, end-start, total),
			TotalCount: int32(total),
		}, nil
	}
	files, err := r.Pulls.Files(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	total := len(files)
	start, end := page.window(total)
	nodes := make([]*gqlmodel.PullRequestChangedFile, 0, end-start)
	for _, f := range files[start:end] {
		nodes = append(nodes, r.URLs.GQLPullRequestChangedFile(f))
	}
	return &gqlmodel.PullRequestChangedFileConnection{
		Nodes:      nodes,
		PageInfo:   pageInfoFor(start, end-start, total),
		TotalCount: int32(total),
	}, nil
}

// Reviews is the resolver for the reviews field. It reads the pull request's
// submitted reviews through the review service on demand.
func (r *pullRequestResolver) Reviews(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*generated.PullRequestReviewConnection, error) {
	page, err := issuePageArgs(ctx, first, after, nil, nil)
	if err != nil {
		return nil, err
	}
	revs, err := r.Resolver.Reviews.ListReviews(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	return r.buildReviewConnection(ctx, revs, page, obj.RepoOwner, obj.RepoName), nil
}

// LatestReviews is the resolver for the latestReviews field. It folds the
// submitted reviews down to the most recent one per reviewer, the summary set
// gh pr view selects with latestReviews(first: 100).
func (r *pullRequestResolver) LatestReviews(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*generated.PullRequestReviewConnection, error) {
	page, err := issuePageArgs(ctx, first, after, nil, nil)
	if err != nil {
		return nil, err
	}
	revs, err := r.Resolver.Reviews.ListReviews(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	return r.buildReviewConnection(ctx, latestReviewsOf(revs), page, obj.RepoOwner, obj.RepoName), nil
}

// ReviewRequests is the resolver for the reviewRequests field. It returns the
// pull request's currently requested reviewers, the set requestReviews
// persists, so a client that requests a reviewer and reads the connection back
// sees them. A first: argument caps the page; teams are not modeled, so every
// node is a User.
func (r *pullRequestResolver) ReviewRequests(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*generated.ReviewRequestConnection, error) {
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	reviewers := pr.RequestedReviewers
	total := int32(len(reviewers))
	if first != nil && *first >= 0 && int(*first) < len(reviewers) {
		reviewers = reviewers[:*first]
	}
	nodes := make([]*generated.ReviewRequest, 0, len(reviewers))
	for _, u := range reviewers {
		nodes = append(nodes, &generated.ReviewRequest{
			RequestedReviewer: r.URLs.GQLUser(u, r.format(ctx)),
		})
	}
	return &generated.ReviewRequestConnection{
		Nodes:      nodes,
		PageInfo:   &gqlmodel.PageInfo{},
		TotalCount: total,
	}, nil
}

// Comments is the resolver for the comments field on PullRequest. It reads the
// pull request's issue-level comments through the issue service; not inline review
// comments, which are under reviewThreads.
func (r *pullRequestResolver) Comments(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string, last *int32, before *string) (*gqlmodel.IssueCommentConnection, error) {
	page, err := issuePageArgs(ctx, first, after, last, before)
	if err != nil {
		return nil, err
	}
	total := obj.CommentsCount
	var comments []*domain.Comment
	start := page.offset
	switch {
	case page.backward:
		var end int
		start, end = page.window(int(total))
		comments, err = r.commentsWindow(ctx, obj.RepoOwner, obj.RepoName, int64(obj.Number), start, end)
	case page.seek > 0:
		// The cursor carries the previous page's last comment id; resume past
		// it with a keyset seek instead of replaying the OFFSET scan.
		comments, err = r.Issues.ListCommentsAfter(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number), page.seek, page.limit)
	case page.offset == 0 && loadersFrom(ctx) != nil:
		// First-page preview: batch every node's selection into one query via
		// the loader, the same shape the issue connection takes.
		comments, err = loadersFrom(ctx).CommentsByIssue.Load(ctx, commentsPreviewKey{IssuePK: obj.IssuePK, Limit: page.limit})
		for _, cm := range comments {
			cm.IssueNumber = int64(obj.Number)
		}
	default:
		comments, err = r.Issues.ListComments(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number), int64(page.page()), int64(page.limit))
	}
	if err != nil {
		return nil, mapErr(err)
	}
	nodes := make([]*gqlmodel.IssueComment, 0, len(comments))
	for _, cm := range comments {
		nodes = append(nodes, r.URLs.GQLIssueComment(obj.RepoOwner, obj.RepoName, cm, r.format(ctx)))
	}
	if total < int32(len(nodes)) {
		total = int32(len(nodes))
	}
	var firstID, lastID int64
	if len(comments) > 0 {
		firstID, lastID = comments[0].ID, comments[len(comments)-1].ID
	}
	return &gqlmodel.IssueCommentConnection{
		Nodes:      nodes,
		PageInfo:   pageInfoSeek(start, len(nodes), int(total), firstID, lastID),
		TotalCount: total,
	}, nil
}

// ProjectCards is the resolver for the projectCards field. Githome does not
// implement classic projects; the connection is always empty.
func (r *pullRequestResolver) ProjectCards(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*generated.ProjectCardConnection, error) {
	return emptyProjectCardConnection(), nil
}

// PullRequest is the resolver for the pullRequest field. A missing pull request,
// or one in a repository the actor cannot see, resolves to null plus a
// NOT_FOUND error, the answer GitHub gives.
func (r *repositoryResolver) PullRequest(ctx context.Context, obj *gqlmodel.Repository, number int32) (*gqlmodel.PullRequest, error) {
	owner, name := splitNWO(obj.NameWithOwner)
	pr, err := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, int64(number))
	if errors.Is(err, domain.ErrPullNotFound) || errors.Is(err, domain.ErrRepoNotFound) {
		return nil, notFoundf("Could not resolve to a PullRequest with the number of %d.", number)
	}
	if err != nil {
		return nil, mapErr(err)
	}
	return r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)), nil
}

// PullRequests is the resolver for the pullRequests field. A repository the actor
// cannot see resolves to an empty connection, never an error, so its existence
// does not leak.
func (r *repositoryResolver) PullRequests(ctx context.Context, obj *gqlmodel.Repository, first *int32, after *string, last *int32, before *string, states []gqlmodel.PullRequestState, headRefName *string, baseRefName *string, labels []string, orderBy *generated.IssueOrder) (*gqlmodel.PullRequestConnection, error) {
	page, err := issuePageArgs(ctx, first, after, last, before)
	if err != nil {
		return nil, err
	}
	if page.backward {
		return nil, gqlError{"backward pagination with `last`/`before` is not supported on this connection."}
	}
	owner, name := splitNWO(obj.NameWithOwner)

	// The unfiltered listing in its native newest-first order pages straight
	// through the store. The first page and any cursor carrying a seek key
	// take the keyset path, with the COUNT run only when totalCount is
	// actually selected; legacy offset-only cursors keep the page-number path.
	if headRefName == nil && baseRefName == nil && len(labels) == 0 && defaultPROrder(orderBy) {
		state := pullStateFilter(states)
		if page.seek > 0 || page.offset == 0 {
			prs, hasMore, err := r.Pulls.ListPRsPage(ctx, viewerID(ctx), owner, name, domain.PRQuery{
				State:       state,
				PerPage:     page.limit,
				AfterNumber: page.seek,
			})
			if errors.Is(err, domain.ErrRepoNotFound) {
				return emptyPullRequestConnection(), nil
			}
			if err != nil {
				return nil, mapErr(err)
			}
			total := lazyTotal(page.offset, len(prs), hasMore)
			if totalCountSelected(ctx) {
				if total, err = r.Pulls.CountPRs(ctx, viewerID(ctx), owner, name, state); err != nil {
					return nil, mapErr(err)
				}
			}
			return r.buildPullRequestConnection(ctx, owner, name, prs, total, page.offset), nil
		}
		prs, total, err := r.Pulls.ListPRs(ctx, viewerID(ctx), owner, name, domain.PRQuery{
			State:   state,
			Page:    page.page(),
			PerPage: page.limit,
		})
		if errors.Is(err, domain.ErrRepoNotFound) {
			return emptyPullRequestConnection(), nil
		}
		if err != nil {
			return nil, mapErr(err)
		}
		return r.buildPullRequestConnection(ctx, owner, name, prs, total, page.offset), nil
	}

	// A filter or a non-native order scans the newest pull requests (capped),
	// matches in memory, then windows. gh pr view <branch> lands here through
	// headRefName.
	matched, err := r.scanPullRequests(ctx, owner, name, states, headRefName, baseRefName, labels)
	if errors.Is(err, domain.ErrRepoNotFound) {
		return emptyPullRequestConnection(), nil
	}
	if err != nil {
		return nil, mapErr(err)
	}
	sortPullRequests(matched, orderBy)
	start, end := page.window(len(matched))
	return r.buildPullRequestConnection(ctx, owner, name, matched[start:end], len(matched), start), nil
}

// Commit returns generated.CommitResolver implementation.
func (r *Resolver) Commit() generated.CommitResolver { return &commitResolver{r} }

// Organization returns generated.OrganizationResolver implementation.
func (r *Resolver) Organization() generated.OrganizationResolver { return &organizationResolver{r} }

// PullRequest returns generated.PullRequestResolver implementation.
func (r *Resolver) PullRequest() generated.PullRequestResolver { return &pullRequestResolver{r} }

type commitResolver struct{ *Resolver }
type organizationResolver struct{ *Resolver }
type pullRequestResolver struct{ *Resolver }
