package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strings"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/nodeid"
	"github.com/tamnd/githome/presenter"
)

// CreateRef is the resolver for the createRef field. gh api and automation that
// creates branches via GraphQL send this mutation.
func (r *mutationResolver) CreateRef(ctx context.Context, input generated.CreateRefInput) (*generated.CreateRefPayload, error) {
	repo, err := r.repoFromID(ctx, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	owner, name := repo.Owner.Login, repo.Name
	ref, err := r.Repos.CreateRef(ctx, viewerID(ctx), owner, name, input.Name, string(input.Oid))
	if err != nil {
		return nil, mapErr(err)
	}
	shortName := ref.Name
	if i := strings.LastIndex(ref.Name, "/"); i >= 0 {
		shortName = ref.Name[i+1:]
	}
	return &generated.CreateRefPayload{
		Ref:              presenter.GQLRef(repo.PK, ref.Name, shortName, ref.Target),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// DeleteRef is the resolver for the deleteRef field. gh api and automation that
// deletes branches via GraphQL send this mutation.
func (r *mutationResolver) DeleteRef(ctx context.Context, input generated.DeleteRefInput) (*generated.DeleteRefPayload, error) {
	repoPK, refName, err := nodeid.DecodeRef(input.RefID)
	if err != nil {
		return nil, unresolvable("Ref", input.RefID)
	}
	repo, rErr := r.Repos.GetRepoByPK(ctx, viewerID(ctx), repoPK)
	if rErr != nil {
		return nil, mapErr(rErr)
	}
	owner, name := repo.Owner.Login, repo.Name
	if err := r.Repos.DeleteRef(ctx, viewerID(ctx), owner, name, refName); err != nil {
		return nil, mapErr(err)
	}
	return &generated.DeleteRefPayload{ClientMutationID: input.ClientMutationID}, nil
}

// CreateBranchProtectionRule is the resolver for the createBranchProtectionRule
// field. Githome does not yet implement branch protection rules; this stub
// returns an empty rule so tooling that creates them does not hard-fail.
func (r *mutationResolver) CreateBranchProtectionRule(_ context.Context, input generated.CreateBranchProtectionRuleInput) (*generated.CreateBranchProtectionRulePayload, error) {
	return &generated.CreateBranchProtectionRulePayload{
		BranchProtectionRule: &generated.BranchProtectionRule{
			ID: branchProtectionRuleID,
		},
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// UpdateBranchProtectionRule is the resolver for the updateBranchProtectionRule
// field. Stub: no-op, returns the rule unchanged.
func (r *mutationResolver) UpdateBranchProtectionRule(_ context.Context, input generated.UpdateBranchProtectionRuleInput) (*generated.UpdateBranchProtectionRulePayload, error) {
	return &generated.UpdateBranchProtectionRulePayload{
		BranchProtectionRule: &generated.BranchProtectionRule{
			ID: input.BranchProtectionRuleID,
		},
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// DeleteBranchProtectionRule is the resolver for the deleteBranchProtectionRule
// field. Stub: no-op, always succeeds.
func (r *mutationResolver) DeleteBranchProtectionRule(_ context.Context, input generated.DeleteBranchProtectionRuleInput) (*generated.DeleteBranchProtectionRulePayload, error) {
	return &generated.DeleteBranchProtectionRulePayload{ClientMutationID: input.ClientMutationID}, nil
}
