package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strings"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/nodeid"
	"github.com/tamnd/githome/presenter"
)

// CreateRef is the resolver for the createRef field. gh api and automation that
// creates branches via GraphQL send this mutation.
func (r *mutationResolver) CreateRef(ctx context.Context, input generated.CreateRefInput) (*generated.CreateRefPayload, error) {
	repo, err := r.repoFromID(ctx, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	owner, name := repo.Owner.Login, repo.Name
	ref, err := r.Repos.CreateRef(ctx, viewerID(ctx), owner, name, input.Name, string(input.Oid))
	if err != nil {
		return nil, mapErr(err)
	}
	shortName := ref.Name
	if i := strings.LastIndex(ref.Name, "/"); i >= 0 {
		shortName = ref.Name[i+1:]
	}
	return &generated.CreateRefPayload{
		Ref:              presenter.GQLRef(repo.ID, ref.Name, shortName, ref.Target),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// DeleteRef is the resolver for the deleteRef field. gh api and automation that
// deletes branches via GraphQL send this mutation.
func (r *mutationResolver) DeleteRef(ctx context.Context, input generated.DeleteRefInput) (*generated.DeleteRefPayload, error) {
	tag, repoID, refName, err := nodeid.DecodeGitObject(input.RefID)
	if err != nil || tag != "ref" {
		return nil, unresolvable("Ref", input.RefID)
	}
	repo, rErr := r.Repos.GetRepoByID(ctx, viewerID(ctx), repoID)
	if rErr != nil {
		return nil, mapErr(rErr)
	}
	owner, name := repo.Owner.Login, repo.Name
	if err := r.Repos.DeleteRef(ctx, viewerID(ctx), owner, name, refName); err != nil {
		return nil, mapErr(err)
	}
	return &generated.DeleteRefPayload{ClientMutationID: input.ClientMutationID}, nil
}

// UpdateRef is the resolver for the updateRef field. It points an existing
// reference at a new commit; gh's branch-sync path sends it. force allows a
// non-fast-forward update, matching GitHub's force flag.
func (r *mutationResolver) UpdateRef(ctx context.Context, input generated.UpdateRefInput) (*generated.UpdateRefPayload, error) {
	tag, repoID, refName, err := nodeid.DecodeGitObject(input.RefID)
	if err != nil || tag != "ref" {
		return nil, unresolvable("Ref", input.RefID)
	}
	repo, rErr := r.Repos.GetRepoByID(ctx, viewerID(ctx), repoID)
	if rErr != nil {
		return nil, mapErr(rErr)
	}
	owner, name := repo.Owner.Login, repo.Name
	force := input.Force != nil && *input.Force
	ref, err := r.Repos.UpdateRef(ctx, viewerID(ctx), owner, name, refName, string(input.Oid), force)
	if err != nil {
		return nil, mapErr(err)
	}
	shortName := ref.Name
	if i := strings.LastIndex(ref.Name, "/"); i >= 0 {
		shortName = ref.Name[i+1:]
	}
	return &generated.UpdateRefPayload{
		Ref:              presenter.GQLRef(repo.ID, ref.Name, shortName, ref.Target),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// CreateBranchProtectionRule is the resolver for the createBranchProtectionRule
// field. Githome does not implement branch protection rules. Returning a fake
// rule with a sentinel id let a client believe protection was in force when it
// was not, so this returns the UNPROCESSABLE error GitHub returns when a rule
// cannot be created rather than a rule that does nothing.
func (r *mutationResolver) CreateBranchProtectionRule(ctx context.Context, input generated.CreateBranchProtectionRuleInput) (*generated.CreateBranchProtectionRulePayload, error) {
	return nil, unprocessablef("Branch protection rules are not supported.")
}

// UpdateBranchProtectionRule is the resolver for the updateBranchProtectionRule
// field. As with creation, Githome stores no rules, so it reports
// UNPROCESSABLE rather than echo back a rule it never changed.
func (r *mutationResolver) UpdateBranchProtectionRule(ctx context.Context, input generated.UpdateBranchProtectionRuleInput) (*generated.UpdateBranchProtectionRulePayload, error) {
	return nil, unprocessablef("Branch protection rules are not supported.")
}

// DeleteBranchProtectionRule is the resolver for the deleteBranchProtectionRule
// field. There are no rules to delete, so it reports UNPROCESSABLE rather than
// a hollow success.
func (r *mutationResolver) DeleteBranchProtectionRule(ctx context.Context, input generated.DeleteBranchProtectionRuleInput) (*generated.DeleteBranchProtectionRulePayload, error) {
	return nil, unprocessablef("Branch protection rules are not supported.")
}
