package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/domain"
	"github.com/tamnd/githome/presenter"
	"github.com/tamnd/githome/presenter/gqlmodel"
)

// StatusCheckRollup is the resolver for the statusCheckRollup field. It folds the
// commit's statuses and check runs through the checks service. A commit with no
// reported status or check has no rollup, so it resolves to null the way GitHub
// leaves statusCheckRollup unset until the first report lands.
func (r *commitResolver) StatusCheckRollup(ctx context.Context, obj *gqlmodel.Commit) (*gqlmodel.StatusCheckRollup, error) {
	rollup, err := r.Checks.Rollup(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, string(obj.Oid))
	if err != nil {
		return nil, mapErr(err)
	}
	if rollup.TotalCount == 0 {
		return nil, nil
	}
	return presenter.GQLStatusCheckRollup(rollup), nil
}

// ResolveReviewThread is the resolver for the resolveReviewThread field. It marks
// a conversation resolved and returns the updated thread.
func (r *mutationResolver) ResolveReviewThread(ctx context.Context, input generated.ResolveReviewThreadInput) (*generated.ResolveReviewThreadPayload, error) {
	thread, err := r.setThreadResolved(ctx, input.ThreadID, true)
	if err != nil {
		return nil, err
	}
	return &generated.ResolveReviewThreadPayload{Thread: thread, ClientMutationID: input.ClientMutationID}, nil
}

// UnresolveReviewThread is the resolver for the unresolveReviewThread field. It
// reopens a resolved conversation and returns the updated thread.
func (r *mutationResolver) UnresolveReviewThread(ctx context.Context, input generated.UnresolveReviewThreadInput) (*generated.UnresolveReviewThreadPayload, error) {
	thread, err := r.setThreadResolved(ctx, input.ThreadID, false)
	if err != nil {
		return nil, err
	}
	return &generated.UnresolveReviewThreadPayload{Thread: thread, ClientMutationID: input.ClientMutationID}, nil
}

// AddPullRequestReview is the resolver for the addPullRequestReview field. gh pr
// review sends this mutation to open a review (optionally submitting immediately
// with an event like APPROVE or REQUEST_CHANGES).
func (r *mutationResolver) AddPullRequestReview(ctx context.Context, input generated.AddPullRequestReviewInput) (*generated.AddPullRequestReviewPayload, error) {
	owner, name, number, err := r.prRefFromID(ctx, input.PullRequestID)
	if err != nil {
		return nil, err
	}
	ri := domain.ReviewInput{}
	if input.Event != nil {
		ri.Event = string(*input.Event)
	}
	if input.Body != nil {
		ri.Body = *input.Body
	}
	if input.CommitOid != nil {
		ri.CommitID = string(*input.CommitOid)
	}
	for _, c := range input.Comments {
		if c == nil {
			continue
		}
		ci := domain.ReviewCommentInput{
			Path: c.Path,
			Body: c.Body,
		}
		if c.Side != nil {
			ci.Side = string(*c.Side)
		}
		if c.Line != nil {
			l := int64(*c.Line)
			ci.Line = &l
		}
		if c.StartLine != nil {
			sl := int64(*c.StartLine)
			ci.StartLine = &sl
		}
		if c.Position != nil {
			p := int64(*c.Position)
			ci.Position = &p
		}
		ri.Comments = append(ri.Comments, ci)
	}
	review, err := r.Reviews.CreateReview(ctx, viewerID(ctx), owner, name, number, ri)
	if err != nil {
		return nil, mapErr(err)
	}
	rev := gqlReview(review, r.URLs, owner, name, r.NodeFormat)
	return &generated.AddPullRequestReviewPayload{
		PullRequestReview: rev,
		ReviewEdge: &generated.PullRequestReviewEdge{
			Cursor: encodeCursor(0),
			Node:   rev,
		},
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// SubmitPullRequestReview is the resolver for the submitPullRequestReview field.
// gh pr review --submit sends this mutation to submit a pending draft review.
func (r *mutationResolver) SubmitPullRequestReview(ctx context.Context, input generated.SubmitPullRequestReviewInput) (*generated.SubmitPullRequestReviewPayload, error) {
	reviewDBID, err := reviewDBIDFromID(input.PullRequestReviewID)
	if err != nil {
		return nil, err
	}
	owner, name, number, err := r.Reviews.ReviewRef(ctx, viewerID(ctx), reviewDBID)
	if err != nil {
		return nil, mapErr(err)
	}
	body := ""
	if input.Body != nil {
		body = *input.Body
	}
	review, err := r.Reviews.SubmitReview(ctx, viewerID(ctx), owner, name, number, reviewDBID, string(input.Event), body)
	if err != nil {
		return nil, mapErr(err)
	}
	return &generated.SubmitPullRequestReviewPayload{
		PullRequestReview: gqlReview(review, r.URLs, owner, name, r.NodeFormat),
		ClientMutationID:  input.ClientMutationID,
	}, nil
}

// ReviewDecision is the resolver for the reviewDecision field. It returns the
// pull request's derived review decision, null when no submitted review blocks or
// approves it.
func (r *pullRequestResolver) ReviewDecision(ctx context.Context, obj *gqlmodel.PullRequest) (*gqlmodel.PullRequestReviewDecision, error) {
	decision, err := r.Reviews.ReviewDecision(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	return presenter.GQLReviewDecision(decision), nil
}

// ReviewThreads is the resolver for the reviewThreads field. It reads the pull
// request's review conversations through the review service on demand.
func (r *pullRequestResolver) ReviewThreads(ctx context.Context, obj *gqlmodel.PullRequest, first *int32, after *string) (*gqlmodel.PullRequestReviewThreadConnection, error) {
	if _, err := issuePageArgs(first, after, nil, nil); err != nil {
		return nil, err
	}
	threads, err := r.Reviews.ReviewThreads(ctx, viewerID(ctx), obj.RepoOwner, obj.RepoName, int64(obj.Number))
	if err != nil {
		return nil, mapErr(err)
	}
	nodes := make([]*gqlmodel.PullRequestReviewThread, 0, len(threads))
	for _, th := range threads {
		nodes = append(nodes, r.URLs.GQLReviewThread(obj.RepoOwner, obj.RepoName, th, r.NodeFormat))
	}
	return &gqlmodel.PullRequestReviewThreadConnection{Nodes: nodes, TotalCount: int32(len(nodes))}, nil
}

// Comments is the resolver for the comments field. The presenter already folded
// the thread's comments into the connection on the parent thread, so the resolver
// validates the page arguments and returns it.
func (r *pullRequestReviewThreadResolver) Comments(_ context.Context, obj *gqlmodel.PullRequestReviewThread, first *int32, after *string) (*gqlmodel.PullRequestReviewCommentConnection, error) {
	if _, err := issuePageArgs(first, after, nil, nil); err != nil {
		return nil, err
	}
	if obj.Comments != nil {
		return obj.Comments, nil
	}
	return &gqlmodel.PullRequestReviewCommentConnection{}, nil
}

// PullRequestReviewThread returns generated.PullRequestReviewThreadResolver implementation.
func (r *Resolver) PullRequestReviewThread() generated.PullRequestReviewThreadResolver {
	return &pullRequestReviewThreadResolver{r}
}

type pullRequestReviewThreadResolver struct{ *Resolver }
