package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"strings"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/auth"
	"github.com/tamnd/githome/domain"
	"github.com/tamnd/githome/git"
	"github.com/tamnd/githome/presenter"
	"github.com/tamnd/githome/presenter/gqlmodel"
)

// Repository is the resolver for the repository field. It resolves the
// repository for the request actor and renders it with its default-branch ref.
// A repository that does not exist or that the actor cannot see resolves to
// null, never an error, so a private repo's existence does not leak.
func (r *queryResolver) Repository(ctx context.Context, owner string, name string) (*gqlmodel.Repository, error) {
	actor := auth.ActorFrom(ctx)
	repo, err := r.Repos.GetRepo(ctx, actor.UserID, owner, name)
	if errors.Is(err, domain.ErrRepoNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	// The default-branch ref is null for a repository with no commits.
	var branch *git.Branch
	if b, err := r.Repos.DefaultBranchRef(repo); err == nil {
		branch = &b
	} else if !errors.Is(err, domain.ErrEmptyRepo) {
		return nil, err
	}

	out := r.URLs.GQLRepository(repo, branch, r.NodeFormat)
	return &out, nil
}

// Viewer returns the currently authenticated user. An anonymous request returns
// null, matching GitHub's behavior for unauthenticated viewer queries.
func (r *queryResolver) Viewer(ctx context.Context) (*gqlmodel.User, error) {
	actor := auth.ActorFrom(ctx)
	if actor.UserID == 0 {
		return nil, nil
	}
	u, err := r.Users.Viewer(ctx, actor.UserID)
	if err != nil {
		return nil, nil
	}
	return r.URLs.GQLUser(u, r.NodeFormat), nil
}

// User resolves a public user profile by login. A missing user resolves to null,
// never an error, matching GitHub's behavior.
func (r *queryResolver) User(ctx context.Context, login string) (*gqlmodel.User, error) {
	u, err := r.Users.ByLogin(ctx, login)
	if errors.Is(err, domain.ErrUserNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.URLs.GQLUser(u, r.NodeFormat), nil
}

// Ref resolves a single reference in the repository by its fully qualified name
// (refs/heads/main, refs/tags/v1.0.0). A missing or invalid ref resolves to
// null, never an error, matching GitHub's behavior.
func (r *repositoryResolver) Ref(ctx context.Context, obj *gqlmodel.Repository, qualifiedName string) (*gqlmodel.Ref, error) {
	owner, name := splitNWO(obj.NameWithOwner)
	repo, err := r.Repos.GetRepo(ctx, viewerID(ctx), owner, name)
	if err != nil {
		return nil, nil
	}
	ref, err := r.Repos.GetRef(repo, qualifiedName)
	if err != nil {
		return nil, nil
	}
	shortName := qualifiedName
	if i := strings.LastIndex(qualifiedName, "/"); i >= 0 {
		shortName = qualifiedName[i+1:]
	}
	return presenter.GQLRef(repo.PK, qualifiedName, shortName, ref.Target), nil
}

// PrimaryLanguage returns the repository's primary programming language. Githome
// does not track per-file language statistics, so this is always null.
func (r *repositoryResolver) PrimaryLanguage(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.Language, error) {
	return nil, nil
}

// LicenseInfo returns the repository's license. Githome does not parse SPDX
// identifiers from repository trees, so this is always null.
func (r *repositoryResolver) LicenseInfo(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.License, error) {
	return nil, nil
}

// Owner returns the repository owner. It looks up the owner's full profile so
// the URL and avatar are present; on any error it falls back to just the login.
func (r *repositoryResolver) Owner(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.RepositoryOwner, error) {
	u, err := r.Users.ByLogin(ctx, obj.RepoOwner)
	if err != nil {
		return &gqlmodel.RepositoryOwner{Login: obj.RepoOwner}, nil
	}
	return r.URLs.GQLRepositoryOwner(u, r.NodeFormat), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Repository returns generated.RepositoryResolver implementation.
func (r *Resolver) Repository() generated.RepositoryResolver { return &repositoryResolver{r} }

type queryResolver struct{ *Resolver }
type repositoryResolver struct{ *Resolver }
