package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/tamnd/githome/api/graphql/generated"
	"github.com/tamnd/githome/auth"
	"github.com/tamnd/githome/domain"
	"github.com/tamnd/githome/git"
	"github.com/tamnd/githome/presenter"
	"github.com/tamnd/githome/presenter/gqlmodel"
)

// Repository is the resolver for the repository field. It resolves the
// repository for the request actor and renders it with its default-branch ref.
// A repository that does not exist or that the actor cannot see resolves to
// null plus a NOT_FOUND error, the same answer in both cases so a private
// repo's existence does not leak.
func (r *queryResolver) Repository(ctx context.Context, owner string, name string) (*gqlmodel.Repository, error) {
	actor := auth.ActorFrom(ctx)
	repo, err := r.Repos.GetRepo(ctx, actor.UserID, owner, name)
	if errors.Is(err, domain.ErrRepoNotFound) {
		return nil, notFoundf("Could not resolve to a Repository with the name '%s/%s'.", owner, name)
	}
	if err != nil {
		return nil, err
	}

	// The default-branch ref is null for a repository with no commits.
	var branch *git.Branch
	if b, err := r.Repos.DefaultBranchRef(repo); err == nil {
		branch = &b
	} else if !errors.Is(err, domain.ErrEmptyRepo) {
		return nil, err
	}

	out := r.URLs.GQLRepository(repo, branch, r.format(ctx))
	return &out, nil
}

// Viewer returns the currently authenticated user. The transport rejects
// anonymous requests with a 401 before execution, so the zero-actor guard here
// is only a backstop for handlers built without an auth service.
func (r *queryResolver) Viewer(ctx context.Context) (*gqlmodel.User, error) {
	actor := auth.ActorFrom(ctx)
	if actor.UserID == 0 {
		return nil, nil
	}
	u, err := r.Users.Viewer(ctx, actor.UserID)
	if err != nil {
		return nil, nil
	}
	return r.URLs.GQLUser(u, r.format(ctx)), nil
}

// User resolves a public user profile by login. A missing user resolves to null,
// never an error, matching GitHub's behavior.
func (r *queryResolver) User(ctx context.Context, login string) (*gqlmodel.User, error) {
	u, err := r.Users.ByLogin(ctx, login)
	if errors.Is(err, domain.ErrUserNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.URLs.GQLUser(u, r.format(ctx)), nil
}

// RepositoryOwner is the resolver for the repositoryOwner field. It looks up
// the user by login and returns a RepositoryOwner view, or null when the login
// does not exist (matching GitHub's behavior).
func (r *queryResolver) RepositoryOwner(ctx context.Context, login string) (gqlmodel.RepositoryOwner, error) {
	u, err := r.Users.ByLogin(ctx, login)
	if errors.Is(err, domain.ErrUserNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.URLs.GQLRepositoryOwner(u, r.format(ctx)), nil
}

// Node is the resolver for the node(id) field. It decodes the opaque node ID,
// dispatches to the matching domain service, and returns the node, or null
// plus a NOT_FOUND error when the id is malformed or does not resolve to a
// live object, GitHub's answer in both cases.
func (r *queryResolver) Node(ctx context.Context, id string) (generated.Node, error) {
	node, err := r.resolveNode(ctx, id)
	if err != nil {
		return nil, err
	}
	if node == nil {
		return nil, notFoundf("Could not resolve to a node with the global id of '%s'.", id)
	}
	return node, nil
}

// Nodes is the resolver for the nodes(ids) field. It resolves each id
// independently and leaves null in each slot that does not resolve; only a
// real failure (not a missing object) fails the list. GitHub caps the ids
// argument at 100 per request, and so does Githome.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]generated.Node, error) {
	if len(ids) > maxNodeIDs {
		return nil, gqlError{"You may not provide more than 100 node ids."}
	}
	out := make([]generated.Node, len(ids))
	for i, id := range ids {
		node, err := r.resolveNode(ctx, id)
		if err != nil {
			return nil, err
		}
		out[i] = node
	}
	return out, nil
}

// RateLimit is the resolver for the rateLimit field. It reports GitHub's
// rate-limit shape against this document: the node count and point cost the
// node-count walk computes for the in-flight operation, charged against the
// fixed hourly budget. Githome does not deduct from the budget across requests,
// so used is this call's cost and remaining is the budget less that cost.
func (r *queryResolver) RateLimit(ctx context.Context) (*gqlmodel.RateLimit, error) {
	nodeCount, cost := queryCost(ctx)
	return &gqlmodel.RateLimit{
		Limit:     rateLimitBudget,
		Cost:      int32(cost),
		Remaining: int32(rateLimitBudget - cost),
		Used:      int32(cost),
		NodeCount: int32(nodeCount),
		ResetAt:   gqlmodel.NewDateTime(time.Now().UTC().Add(time.Hour)),
	}, nil
}

// Search is the resolver for the search field. It fans out to the domain search
// service depending on the requested type. Only REPOSITORY and ISSUE are
// implemented today; other types return an empty connection.
func (r *queryResolver) Search(ctx context.Context, query string, typeArg generated.SearchType, first *int32, after *string) (*generated.SearchResultItemConnection, error) {
	limit := int32(30)
	if first != nil && *first > 0 {
		limit = *first
		if limit > 100 {
			limit = 100
		}
	}
	conn := &generated.SearchResultItemConnection{
		PageInfo: &gqlmodel.PageInfo{},
	}
	switch typeArg {
	case generated.SearchTypeRepository:
		repos, total, err := r.SearchSvc.SearchRepositories(ctx, viewerID(ctx), query, "updated", "desc", 1, int(limit))
		if err != nil {
			return nil, mapErr(err)
		}
		nodes := make([]generated.SearchResultItem, 0, len(repos))
		for _, repo := range repos {
			var branch *git.Branch
			if b, e := r.Repos.DefaultBranchRef(repo); e == nil {
				branch = &b
			}
			out := r.URLs.GQLRepository(repo, branch, r.format(ctx))
			nodes = append(nodes, out)
		}
		conn.Nodes = nodes
		conn.RepositoryCount = int32(total)
	case generated.SearchTypeIssue:
		hits, total, err := r.SearchSvc.SearchIssues(ctx, viewerID(ctx), query, "created", "desc", 1, int(limit))
		if err != nil {
			return nil, mapErr(err)
		}
		nodes := make([]generated.SearchResultItem, 0, len(hits))
		for _, h := range hits {
			owner, name := h.Repo.Owner.Login, h.Repo.Name
			// An ISSUE search spans issues and pull requests; an is:pr hit
			// must come back as a PullRequest node or gh pr status's
			// ... on PullRequest fragments select nothing.
			if h.Issue.IsPull {
				pr, pErr := r.Pulls.GetPR(ctx, viewerID(ctx), owner, name, h.Issue.Number)
				if pErr != nil {
					continue
				}
				nodes = append(nodes, r.URLs.GQLPullRequest(owner, name, pr, r.format(ctx)))
				continue
			}
			nodes = append(nodes, r.URLs.GQLIssue(owner, name, h.Issue, r.format(ctx)))
		}
		conn.Nodes = nodes
		conn.IssueCount = int32(total)
	}
	conn.Edges = make([]*generated.SearchResultItemEdge, 0, len(conn.Nodes))
	for i, node := range conn.Nodes {
		conn.Edges = append(conn.Edges, &generated.SearchResultItemEdge{Cursor: encodeCursor(i + 1), Node: node})
	}
	return conn, nil
}

// ViewerPermission is the resolver for the viewerPermission field. The presenter
// computes the permission when it renders the repository; return it as-is. It is
// null for an anonymous viewer.
func (r *repositoryResolver) ViewerPermission(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.RepositoryPermission, error) {
	return obj.ViewerPermission, nil
}

// Parent is the resolver for the parent field. A fork carries the parent's
// internal pk; the resolver loads that repository for the viewer and renders it
// with its default-branch ref. A non-fork (or a parent the viewer cannot see)
// resolves to null, matching GitHub.
func (r *repositoryResolver) Parent(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.Repository, error) {
	if obj.ForkParentPK == nil {
		return nil, nil
	}
	parent, err := r.Repos.GetRepoByPK(ctx, viewerID(ctx), *obj.ForkParentPK)
	if err != nil {
		return nil, nil
	}
	var branch *git.Branch
	if b, err := r.Repos.DefaultBranchRef(parent); err == nil {
		branch = &b
	}
	out := r.URLs.GQLRepository(parent, branch, r.format(ctx))
	return &out, nil
}

// Milestones is the resolver for the milestones field. It lists the repository's
// milestones filtered by the requested states, optionally narrowed by a title
// query substring, and paged by first (default 30). gh's milestone picker reads
// it during issue and pull-request creation.
func (r *repositoryResolver) Milestones(ctx context.Context, obj *gqlmodel.Repository, first *int32, after *string, states []generated.MilestoneState, orderBy *generated.MilestoneOrder, query *string) (*gqlmodel.MilestoneConnection, error) {
	owner, name := splitNWO(obj.NameWithOwner)
	all, err := r.Resolver.Issues.ListMilestones(ctx, viewerID(ctx), owner, name, milestoneStateFilter(states))
	if err != nil {
		return nil, mapErr(err)
	}
	conn := &gqlmodel.MilestoneConnection{Nodes: []*gqlmodel.Milestone{}, PageInfo: &gqlmodel.PageInfo{}}
	limit := 30
	if first != nil && *first >= 0 {
		limit = int(*first)
	}
	for _, m := range all {
		if query != nil && *query != "" && !strings.Contains(strings.ToLower(m.Title), strings.ToLower(*query)) {
			continue
		}
		conn.Nodes = append(conn.Nodes, r.URLs.GQLMilestone(owner, name, m, r.format(ctx)))
	}
	conn.TotalCount = int32(len(conn.Nodes))
	if len(conn.Nodes) > limit {
		conn.Nodes = conn.Nodes[:limit]
		conn.PageInfo.HasNextPage = true
	}
	return conn, nil
}

// LatestRelease is the resolver for the latestRelease field. It returns the
// repository's most recent published release, or null when there are none or
// the release service is not wired. gh repo view selects it.
func (r *repositoryResolver) LatestRelease(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.Release, error) {
	if r.Releases == nil {
		return nil, nil
	}
	owner, name := splitNWO(obj.NameWithOwner)
	rel, err := r.Releases.GetLatestRelease(ctx, viewerID(ctx), owner, name)
	if errors.Is(err, domain.ErrReleaseNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, nil
	}
	return r.URLs.GQLRelease(owner, name, rel, true, r.format(ctx)), nil
}

// Ref resolves a single reference in the repository by its fully qualified name
// (refs/heads/main, refs/tags/v1.0.0). A missing or invalid ref resolves to
// null, never an error, matching GitHub's behavior.
func (r *repositoryResolver) Ref(ctx context.Context, obj *gqlmodel.Repository, qualifiedName string) (*gqlmodel.Ref, error) {
	owner, name := splitNWO(obj.NameWithOwner)
	repo, err := r.Repos.GetRepo(ctx, viewerID(ctx), owner, name)
	if err != nil {
		return nil, nil
	}
	ref, err := r.Repos.GetRef(repo, qualifiedName)
	if err != nil {
		return nil, nil
	}
	shortName := qualifiedName
	if i := strings.LastIndex(qualifiedName, "/"); i >= 0 {
		shortName = qualifiedName[i+1:]
	}
	return presenter.GQLRef(repo.ID, qualifiedName, shortName, ref.Target), nil
}

// PrimaryLanguage returns the repository's primary programming language. Githome
// does not track per-file language statistics, so this is always null.
func (r *repositoryResolver) PrimaryLanguage(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.Language, error) {
	return nil, nil
}

// LicenseInfo returns the repository's license. Githome does not parse SPDX
// identifiers from repository trees, so this is always null.
func (r *repositoryResolver) LicenseInfo(ctx context.Context, obj *gqlmodel.Repository) (*gqlmodel.License, error) {
	return nil, nil
}

// Owner returns the repository owner. It looks up the owner's full profile so
// the URL and avatar are present; on any error it falls back to just the login.
func (r *repositoryResolver) Owner(ctx context.Context, obj *gqlmodel.Repository) (gqlmodel.RepositoryOwner, error) {
	u, err := r.Users.ByLogin(ctx, obj.RepoOwner)
	if err != nil {
		return &gqlmodel.User{Login: obj.RepoOwner}, nil
	}
	return r.URLs.GQLRepositoryOwner(u, r.format(ctx)), nil
}

// AvatarURL is the resolver for the avatarUrl field. The presenter fills the
// base avatar URL; when the client requests a size, append the same `?s=`
// query GitHub uses so the stored image is scaled to a square that many pixels.
func (r *userResolver) AvatarURL(ctx context.Context, obj *gqlmodel.User, size *int32) (gqlmodel.URI, error) {
	return avatarWithSize(obj.AvatarURL, size), nil
}

// IsViewer is the resolver for the isViewer field. A user is the viewer when
// their login matches the authenticated actor's; an anonymous actor is nobody.
func (r *userResolver) IsViewer(ctx context.Context, obj *gqlmodel.User) (bool, error) {
	login := auth.ActorFrom(ctx).UserLogin
	return login != "" && login == obj.Login, nil
}

// Repositories is the resolver for the repositories field on User.
// It lists all visible repositories for the user's login.
func (r *userResolver) Repositories(ctx context.Context, obj *gqlmodel.User, first *int32, after *string, ownerAffiliations []generated.RepositoryAffiliation, isArchived *bool, isFork *bool, privacy *generated.RepositoryPrivacy, orderBy *generated.RepositoryOrder) (*gqlmodel.RepositoryConnection, error) {
	return r.listReposForLogin(ctx, obj.Login, first)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Repository returns generated.RepositoryResolver implementation.
func (r *Resolver) Repository() generated.RepositoryResolver { return &repositoryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type queryResolver struct{ *Resolver }
type repositoryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
